README.md, sortinghat/cmd/enroll.py
I ran across these two typos today, and they were bothering me, so I thought I would throw together a pull request to fix them :)
=> corrected small typos in sortinghat enroll help and in README

README.md
Some of these details are about Sorting Hat itself, some others are about how to install it via pip.
I bumped the version label to 0.2.0 as well, to have a relatively stable release that we can upload to pypi.
=> Add some more details about Sorting Hat in README.md

sortinghat/cmd/load.py, tests/test_cmd_load.py
Before loading any data, if 'reset' option is set, all the
relationships between identities and their enrollments will
be removed from the database.
Thus, both input and database will have the same status for
the loaded unique identities.
This commit fixes #94
=> [cmd:load] Add option to clear ids relationships and enrollments

sortinghat/api.py, tests/test_api.py
This function works as 'search_unique_identities' but allows to limit the number of results obtained.
=> [api] Add search_unique_identities_slice() function

README.md
This code includes troubleshooting information which may come in handy to allow the test suite to work. In particular, it shows how to (i) avoid calling mysql using sudo and (ii) disable the mysql strict mode.
=> [readme] Include troubleshooting section

setup.py
Signed-off-by: Valerio Cosentino <valcos@bitergia.com>
=> [setup] Pin pandas dependency

sortinghat/db/database.py, tests/test_model.py
The engine was not configure to accept SSL connections. With this patch, the database module will try to establish a SSL connection first. If this is not possible, it will try to communicate with the server with a non-secure connection.
To set the SSL connection, it was necessary a minor hack that consists on passing an non-empty dictionary with key 'ssl' in 'connect_args'. The module pymysql expects a dict with some SSL paramters, which will force to use specific cert o ca. As we do not want that, we found that passing
a dict with a random key is valid and pymsql ignores that key but enforces a SSL connection.
Take into account this commit does not include tests. Although we want to have tests for every commit, I think this might be an exception due to `database` module does not have …
=> [database] Allow SSL connections

config/settings/testing.py
This patch adds some configuration parameters to the testing settings required to pass the tests.
Signed-off-by: Santiago Dueñas <sduenas@bitergia.com>
=> Add authentication configuration to testing

README.md
Hark, hark! Sir Perceval needs to be linked. 🐴 👑 
(And some very minor pitch change to clarify the first sentence.)
=> Clarifying sortinghat introduction

README.md
Fixes: #284 
This commit add examples of SortingHat API via Python.
A new section Basic API calls was added to include the
example.
Signed-off-by: Animesh Kumar <animuz111@gmail.com>
=> [doc] Add examples of SortingHat API via Python

misc/grimoirelab2sh, sortinghat/parsing/grimoirelab.py, tests/data/grimoirelab_invalid_enrollment_periods.yml, tests/test_parser_grimoirelab.py
Enrollment periods will not be valuated when
`enrollment_periods_validation` is set to `False`
Test added accordingly.
=> [misc/grimoirelab2sh] Add new argument to avoid periods validation

sortinghat/core/jobs.py, sortinghat/core/schema.py, tests/test_jobs.py, tests/test_schema.py
This PR aims to solve issue #299.
This new mutation returns a job which returns a list of recommendations which include the organizations where individuals can be affiliated.
If the input list of individuals is empty, the job will be applied to all the individuals in the registry.
The class `JobType` has been modified to include a new field called `method`, which includes the name of the method that job is executed for, and its value is obtained from the field `func_name` inside the `Job` object. This was needed because the resolver for jobs has to distinguish between different jobs executed in different methods, as they can return values in different ways.
Example for the new mutation:
```
mutation {
recommendAffiliations(uuids: ["<uuid1>", "<uuid2>"]) {
jobId
}
}
```
Query for getting …
=>  Get affiliation recommendations given a set of individuals

ui/package.json, ui/src/App.vue, ui/src/apollo/queries.js, ui/src/components/IndividualsGrid.stories.js, ui/src/components/IndividualsGrid.vue, ui/src/main.js, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/queries.spec.js, ui/yarn.lock
This PRs adds the next functionality:
- Integration of the Apollo library
- Adapt the components to show individuals from GraphQL
- Test of the query used in the component
---
I have a comment @sduenas , I think that the snapshot for the storybook tests has changed (because I had to adapt the IndividualsGrid component), please, let me know If I have to recreate a new one and how to do it.
=> [ui] Add Apollo integration and show invididuals

ui/src/components/ProfileCard.stories.js, ui/src/components/ProfileCard.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
This PR adds a list of enrollments in organizations to the `ProfileCard` component as proposed in #298.
=> [ui] Add list of organization enrollments to ProfileCard

ui/src/App.vue, ui/src/apollo/queries.js, ui/src/components/IndividualsData.vue, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/queries.spec.js
This PR adds the functionality of having an infinite scrolling inside the individual's grid.
Related to #306
=> [ui] Infinite scrolling into the individuals table

ui/src/components/IndividualCard.stories.js, ui/src/components/IndividualCard.vue, ui/src/components/IndividualsGrid.stories.js, ui/src/components/IndividualsGrid.vue, ui/src/components/ProfileCard.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
This PR displays a list of data source icons on the `IndividualCard`
component, passed by a new 'sources' prop from the `ProfileCard`
and `IndividualsGrid`components. The Storybook stories are also
updated to reflect this change.
=> [ui] Data source icons on the IndividualCard 

ui/src/apollo/queries.js, ui/src/components/IndividualCard.stories.js, ui/src/components/IndividualCard.vue, ui/src/components/IndividualsGrid.stories.js, ui/src/components/IndividualsGrid.vue, ui/src/components/ProfileCard.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
This PR adds an icon to the 'IndividualCard' component
to show whether or not the profile is locked as requested in #321 .
This information can be passed through the prop 'isLocked' from the 'ProfileCard'
and 'IndividualsGrid' components.
=> [ui] Add locked/unlocked icon to IndividualCard

ui/src/components/IndividualsData.vue, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/queries.spec.js
This PR fixes the issues that cause the warning messages described in #325.
Signed-off-by: Eva Millán <evamillan@bitergia.com>
=> [ui] Fix new warning messages in unit tests

ui/src/App.vue, ui/src/apollo/queries.js, ui/src/components/Identity.vue, ui/src/components/IndividualCard.vue, ui/src/components/IndividualsData.vue, ui/src/components/IndividualsGrid.vue, ui/src/components/ProfileCard.vue, ui/src/components/ProfileList.vue, ui/src/store/index.js, ui/tests/unit/ProfileList.spec.js, ui/tests/unit/__snapshots__/ProfileList.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/yarn.lock
Adds the `ProfileList` component, which displays a list
of `ProfileCards` when their corresponding `IndividualCard` is selected
on `IndividualsGrid'. The selected cards are stored in the Vuex state
so that they can be retrieved anywhere throughout the app.
=> [ui] Show profile information when clicking on an individual card

ui/src/components/ExpandedIndividual.stories.js, ui/src/components/ExpandedIndividual.vue, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.stories.js, ui/src/components/IndividualsTable.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Adds the `IndividualsTable` component, which displays a
list of `IndividualEntry` rows that can be expanded to
show an individual's identities and affiliations as requested
on #330
=> [ui] Implement Individuals table basic component

ui/src/App.vue, ui/src/apollo/queries.js, ui/src/components/ExpandedIndividual.vue, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.stories.js, ui/src/components/IndividualsTable.vue, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/queries.spec.js
Adds pagination to `IndividualsTable` and embeds the component into `App`. It also adds the `getPaginatedIndividuals` query to retrieve the paginated data needed for the table and tests it.
=> [ui] Add pagination to Individuals table 

ui/src/components/IndividualEntry.stories.js, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.stories.js, ui/src/components/IndividualsTable.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Adds a lock icon next to the individual's name on `IndividualEntry` if their profile is locked.
=> [ui] Add locked visual cue to IndividualEntry

ui/src/apollo/queries.js, ui/src/components/IndividualEntry.stories.js, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.stories.js, ui/src/components/IndividualsTable.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Adds an icon next to an individual's name on `IndividualEntry` if it's a bot.
=> [ui] Add bot visual cue to IndividualEntry

ui/src/App.vue, ui/src/components/IndividualEntry.stories.js, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.vue, ui/src/components/WorkSpace.stories.js, ui/src/components/WorkSpace.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Adds the `WorkSpace` component, which displays a set of individual cards. The individuals can be saved to the work space by clicking the pin button on `IndividualEntry` or dragging and dropping the table row over the space. The work space can be cleared by clicking a button.
=> [ui] Implement basic workspace area

ui/src/components/OrganizationEntry.stories.js, ui/src/components/OrganizationEntry.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Adds the `OrganizationEntry` component, which displays a table row with an organization's name and number of individuals enrolled.
=> [ui] Implement a OrganizationEntry component

ui/src/App.vue, ui/src/apollo/queries.js, ui/src/components/OrganizationEntry.vue, ui/src/components/OrganizationsTable.stories.js, ui/src/components/OrganizationsTable.vue, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/queries.spec.js
Adds the `OrganizationsTable` component, which displays a list of organizations and the number of individuals enrolled in them. It also implements the `getPaginatedOrganizations` query to get this information.
=> [ui] Implement Organizations table component

ui/src/App.vue, ui/src/apollo/mutations.js, ui/src/components/ExpandedIndividual.vue, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.stories.js, ui/src/components/IndividualsTable.vue, ui/src/components/WorkSpace.stories.js, ui/src/components/WorkSpace.vue, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/mutations.spec.js, ui/tests/unit/queries.spec.js
The individuals in `IndividualsTable` can be merged together by selecting them and clicking the merge action button on top, or they can be dragged and dropped into another individual. A dialog appears before the merge to confirm the action.
The `merge` Apollo mutation is used on `App` to perform this action.
=> [ui] Merge individuals table action

ui/src/App.vue, ui/src/apollo/mutations.js, ui/src/components/IndividualsTable.vue, ui/src/components/WorkSpace.stories.js, ui/src/components/WorkSpace.vue, ui/src/utils/actions.js, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Individuals in `WorkSpace` can be merged by clicking the merge icon on top of the component. When merged, the previously saved individuals get replaced by the merged one. Then the work space emits an event to indicate that other components may need to update their individuals.
=> [ui] Merge individuals on the workspace

ui/src/apollo/mutations.js, ui/src/components/IndividualCard.vue, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.vue, ui/src/components/WorkSpace.vue, ui/src/styles/index.scss, ui/src/utils/actions.js, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Individuals can be merged by dragging them from the table and dropping them into an individual card in the workspace. The workspace is then updated with the new individual.
=> [ui] Merge individuals on the workspace using drag and drop 

ui/src/components/IndividualCard.vue, ui/src/components/WorkSpace.stories.js, ui/src/components/WorkSpace.vue, ui/tests/unit/__snapshots__/IndividualCard.spec.js.snap, ui/tests/unit/__snapshots__/ProfileList.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Individuals on the workspace can be selected by clicking on their card. The workspace actions can be performed on the selected individuals.
=> [ui] Select individuals on the workspace

ui/src/components/ExpandedIndividual.stories.js, ui/src/components/ExpandedIndividual.vue, ui/src/components/Identity.vue, ui/src/components/IndividualCard.stories.js, ui/src/components/IndividualCard.vue, ui/src/components/WorkSpace.vue, ui/tests/unit/__snapshots__/IndividualCard.spec.js.snap, ui/tests/unit/__snapshots__/ProfileList.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap
`IndividualCard` shows a compact version of `ExpandedIndividual` when the magnifier icon is clicked, which displays a list of the individual's identities and enrollments.
=> Show extended data on the IndividualCard

ui/src/App.vue, ui/src/components/IndividualCard.stories.js, ui/src/components/IndividualCard.vue, ui/src/components/IndividualEntry.stories.js, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.vue, ui/src/components/WorkSpace.stories.js, ui/src/components/WorkSpace.vue, ui/src/styles/index.scss, ui/tests/unit/__snapshots__/IndividualCard.spec.js.snap, ui/tests/unit/__snapshots__/ProfileList.spec.js.snap, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Individuals on the workspace that are also visible on IndividualsTable display an icon and vice versa. When the user hovers over them, the corresponding individual is highlighted.
=> Highlight Individuals that are on the workspace and on the table

ui/src/components/ExpandedIndividual.stories.js, ui/src/components/Identity.vue, ui/src/components/Indentity.stories.js, ui/src/components/IndividualsTable.stories.js, ui/src/components/WorkSpace.stories.js, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Limits the size of the uuid chip on `IndividualEntry` to 7 characters. The full uuid is displayed on hover.
=> [ui] Improve UUID visualization on IndividualEntry

ui/src/components/ExpandedIndividual.stories.js, ui/src/components/ExpandedIndividual.vue, ui/src/components/IndividualEntry.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Displays known sources first on `IndividualEntry` and `ExpandedIndividual`, and the 'others' sources in alphabetical order.
=> [ui] Display known sources first

ui/src/App.vue, ui/src/apollo/mutations.js, ui/src/components/ExpandedIndividual.vue, ui/src/components/IndividualCard.vue, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.stories.js, ui/src/components/IndividualsTable.vue, ui/src/components/WorkSpace.stories.js, ui/src/components/WorkSpace.vue, ui/src/utils/actions.js, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/mutations.spec.js, ui/tests/unit/queries.spec.js
An individual's identity on `ExpandedIndividual` can be dragged and dropped into an individual's card on the workspace or to another individual's entry on `IndividualsTable`.
A GraphQL mutation is added to allow an identity to be moved.
=> Move Identity to another IndividualEntry or IndividualCard

ui/src/App.vue, ui/src/components/IndividualsTable.vue, ui/src/components/WorkSpace.stories.js, ui/src/components/WorkSpace.vue
Deselects individuals on the `IndividualsTable` when they are dragged and dropped into the workspace.
=> [ui] Deselect individuals when they are added to the workspace

ui/src/App.vue, ui/src/apollo/mutations.js, ui/src/apollo/queries.js, ui/src/components/IndividualsTable.vue, ui/src/components/OrganizationEntry.vue, ui/src/components/OrganizationsTable.stories.js, ui/src/components/OrganizationsTable.vue, ui/src/utils/actions.js, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/mutations.spec.js, ui/tests/unit/queries.spec.js
Individuals can be dragged and dropped from their table into an organization entry to affiliate them. A GraphQL mutation is added to enroll the individuals in the database. `OrganizationsTable` then emits an event to update the information on `IndividualsTable` and `Workspace`.
=> [ui] Affiliate Individuals by dragging & dropping

sortinghat/core/schema.py, tests/test_schema.py
As requested on issue https://github.com/chaoss/grimoirelab-sortinghat/issues/355, now `Individuals` query accepts a search term (filter `term`). This term is searched on the fields `name`, `email` and `username` among the different identities from the individuals on the registry.
=> [schema] Allow search individuals by term

ui/src/apollo/mutations.js, ui/src/components/Dashboard.vue, ui/src/components/ExpandedIndividual.vue, ui/src/components/IndividualsTable.stories.js, ui/src/components/IndividualsTable.vue, ui/src/components/WorkSpace.stories.js, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/mutations.spec.js, ui/tests/unit/queries.spec.js
This PR adds the `withdraw` Apollo mutation, which removes an individual's affiliation to an organization.
An individual's affiliation can be removed by clicking the delete button next to it on `ExpandedIndividual`.
=> [ui] Remove individuals affiliations

ui/src/apollo/mutations.js, ui/src/components/Dashboard.vue, ui/src/components/OrganizationEntry.vue, ui/src/components/OrganizationsTable.stories.js, ui/src/components/OrganizationsTable.vue, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/mutations.spec.js, ui/tests/unit/queries.spec.js
Adds a delete button to `OrganizationEntry` that removes it from the list using the `removeOrganization` Apollo GraphQL mutation. It displays a confirmation modal before the action is performed.
=> [ui] Remove organization

ui/src/components/ExpandedIndividual.vue, ui/src/components/IndividualCard.vue, ui/src/components/IndividualEntry.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Adds a tooltip that shows the datasource name when the cursor is over an icon.
=> [ui] Show dasource name on datasource icons

ui/src/components/OrganizationEntry.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Shows an icon next to the number of individuals affiliated to an organization as requested in #418.
=> [ui] Show affiliation cue in organizations table

ui/src/apollo/mutations.js, ui/src/components/ExpandedIndividual.vue, ui/src/components/IndividualsTable.stories.js, ui/src/components/IndividualsTable.vue, ui/src/components/WorkSpace.stories.js, ui/src/views/Dashboard.vue, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/mutations.spec.js, ui/tests/unit/queries.spec.js
This PR allows users to modify the dates of an individual's enrollment from the UI, using the `updateEnrollment` Apollo mutation.
=> [ui] Edit enrollment dates

ui/src/components/IndividualCard.vue, ui/src/components/IndividualEntry.vue, ui/src/mixins/avatar.js, ui/tests/unit/__snapshots__/storybook.spec.js.snap
This PR adds a Vue mixin that picks a color for an individual's avatar based on their initials. The palette is generated from colors complementary or analogous to Grimoirelab's blue and yellow:
=> [ui] Show different colors on the Individual avatars

ui/src/apollo/queries.js, ui/src/components/WorkSpace.vue, ui/src/store/index.js, ui/src/views/Dashboard.vue
The workspace data is saved on the Vuex store and local storage to prevent it from getting lost when the browser is closed or reloaded.
=> [ui] Save Workspace

ui/src/components/IndividualsTable.stories.js, ui/src/components/IndividualsTable.vue, ui/src/components/WorkSpace.stories.js, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Shows the total number of individuals from a particular query next to the `IndividualsTable`.
=> [ui] Show the total number of individuals

ui/src/components/OrganizationsTable.stories.js, ui/src/components/OrganizationsTable.vue, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Shows the total number of organizations from a particular query next to the `OrganizationsTable`.
=> [ui] Show the total number of organizations

sortinghat/core/schema.py, tests/test_schema.py, ui/src/components/Search.vue, ui/src/views/SearchHelp.vue, ui/tests/unit/queries.spec.js, ui/tests/unit/search.spec.js
Adds the `gender` filter to the` individuals` query, which returns individuals with a given gender.
In the UI Search component, the syntax is `gender:string`.
=> Search individuals by gender

sortinghat/core/schema.py, tests/test_schema.py, ui/src/views/SearchHelp.vue, ui/tests/unit/search.spec.js
Adds the `source` filter to the `individuals` query, which returns a list of individuals whose identities match the given data source.
In the UI Search component, the syntax is `source:"data source"`.
=> Search individuals by data source

ui/src/apollo/mutations.js, ui/src/components/IndividualCard.stories.js, ui/src/components/IndividualCard.vue, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.vue, ui/src/components/OrganizationEntry.vue, ui/src/components/WorkSpace.vue, ui/src/styles/index.scss, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Allows locked individuals on the `IndividualsTable` to be selected and dragged into the workspace. Locked individuals are prevented from being merged or deleted when selected or when dropped into an organization or another individual.
=> [ui] Drag and drop locked individuals into the Workspace

ui/src/components/OrganizationsTable.vue, ui/src/components/Search.stories.js, ui/src/components/Search.vue, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/search.spec.js
Adds the `validFilters` and `showFilters` props to the `Search` component.
- If the user input includes a filter that is not found on the valid filters list, an error is shown.
- With the `showFilters` prop, a dropdown with all valid filters is displayed next to the search box. When a filter is clicked, it is added to the search input.
=> [ui] Show errors for invalid search filters

sortinghat/cli/client/schema.py
This update is needed to use all mutations as:
- affiliate
- unify
- recommended_affiliations
- recommended_matches
- update_enrollment
=> [client/schema.py] Update schema.py

ui/.eslintrc.js, ui/src/components/Avatar.stories.js, ui/src/components/ExpandedIndividual.stories.js, ui/src/components/ExpandedOrganization.stories.js, ui/src/components/Indentity.stories.js, ui/src/components/IndividualCard.stories.js, ui/src/components/IndividualEntry.stories.js, ui/src/components/IndividualsGrid.stories.js, ui/src/components/IndividualsTable.stories.js, ui/src/components/JobsTable.stories.js, ui/src/components/OrganizationEntry.stories.js, ui/src/components/OrganizationModal.stories.js, ui/src/components/OrganizationsTable.stories.js, ui/src/components/ProfileCard.stories.js, ui/src/components/ProfileModal.stories.js, ui/src/components/Search.stories.js, ui/src/components/WorkSpace.stories.js, ui/tests/unit/mutations.spec.js, ui/tests/unit/queries.spec.js, ui/tests/unit/search.spec.js
This PR fixes the eslint errors of the web app code in the muggle branch. This is necessary as we have to add an eslint check in the github actions ci workflow.
=> [ui] Fix eslint errors

ui/src/components/IndividualsTable.vue, ui/src/components/OrganizationsTable.vue, ui/src/components/Search.stories.js, ui/src/components/Search.vue, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/search.spec.js
Adds an optional selector that displays the list of valid filters next to the search input. When a filter is selected from the list, it is added to the input value.
=> [ui] Add filter selector to the search box

poetry.lock, pyproject.toml
Few dependencies are outdated which are causing errors. This PR updates the dependencies using poetry.
=> [deps] Update dependencies

README.md
This commit adds extra steps to install the developing version of SortingHat. These new steps include the installation of `poetry`, `yarn` and other dependencies.
=> Add steps in the documentation to install dependencies

config/settings/devel.py, sortinghat/core/api.py, sortinghat/core/db.py, sortinghat/core/jobs.py, sortinghat/core/log.py, sortinghat/core/recommendations/affiliation.py, sortinghat/core/recommendations/matching.py, tests/test_log.py
Series of commits that add logging messages to the code. This addresses the issue #474.
=> Add logging messages

README.md
This PR updates the README.md file with the steps to apply fixtures after migrations. Without this step, the user cannot assign countries to the Individuals.
Related to https://github.com/chaoss/grimoirelab-sortinghat/issues/503
=> Add fixtures step to the documentation

sortinghat/core/models.py, sortinghat/core/schema.py, tests/test_schema.py, ui/package.json, ui/src/apollo/queries.js, ui/src/components/IndividualsTable.vue, ui/src/components/Search.stories.js, ui/src/components/Search.vue, ui/src/views/Dashboard.vue, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/queries.spec.js, ui/tests/unit/search.spec.js, ui/yarn.lock
This PR allows individuals to be ordered by their last modified date.
- The schema is updated to include an `order_by` argument in `resolve_individuals` (`mk` by default). The `getPaginatedIndividuals` query on the UI is updated accordingly.
- An optional order selector is added to the the `Search` component. When the value or order is changed, it is emitted to the `IndividualsTable`, along with the search filters.
- The `vue-test-utils` version is changed to 1.1.2 because a function used in the tests does not work properly in the previous one.
=> Order individuals by lastModified field

ui/src/components/DateInput.stories.js, ui/src/components/DateInput.vue, ui/src/components/IndividualsTable.vue, ui/src/components/OrganizationsTable.vue, ui/src/components/WorkSpace.vue, ui/src/mixins/enroll.js, ui/src/styles/index.scss, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/dateInput.spec.js
Creates a `DateInput` component, which displays a text input that opens a date picker when touched, and adds an optional form to set the dates on the enrollment dialogs in `IndividualsTable`, `OrganizationsTable` and `Workspace`. The styles of the dialogs are also unified.
Fixes #515.
=> [ui] Set enrollment dates when a new affiliation is created

sortinghat/core/schema.py, tests/test_schema.py, ui/src/components/Search.vue, ui/src/views/SearchHelp.vue, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Adds the `enrollment` filter to the `individuals` query, which returns a list of individuals enrolled in the given organization.
The search syntax in the UI is `enrollment:"organization name"`.
=> Filter individuals by enrollment 

sortinghat/core/schema.py
Adds descriptions to the GraphQL queries and mutations.
=> Add documentation for GraphQL API

tests/test_schema.py
Tests were missing for handling invalid datetime
values for enrollment_date and for some operators
in last_updated filter.
Signed-off-by: sevagenv <sevagenv@gmail.com>
=> [tests] Improve coverage for schema.py

ui/src/main.js
Fixes #531, replacing the deprecated synchronous `XMLHttpRequest` to get the CSRF token with the newer `fetch` API. The request is asynchronous, but the token is retrieved after it is finished, using `then()`.
=> [ui] Fix synchronous request warning

poetry.lock, pyproject.toml
=> [pyproject] Update grimoirelab-toolkit "^0.2.0"

sortinghat/core/schema.py, tests/test_schema.py
Resolves: #568 
This commit adds the `subteams` field to the Team object.
`subteams` can be resolved recursively within the query multiple times.
As a result of adding subteams, this commit modifies the resolver for
Team objects to return teams of only one level at any point of time
unless the `subteams` field is requested in query.
Signed-off-by: Rashmi-K-A <k.a.rashmi04@gmail.com>
=> [schema] Add `subteams` field to Team objects in GraphQL

utils/create_sh_0_7_fixture.py
This code allows the script to create a fixture JSON file
according to the new 'organization' schema.
Also fix the following RuntimeWarning
```
RuntimeWarning: DateTimeField Enrollment.start received a naive
datetime (2000-01-01 00:00:00) while time zone support is active.
```
=> [utils] Update create_sh_0_7_fixture script.

ui/jest-puppeteer.config.js, ui/src/apollo/mutations.js, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.vue, ui/src/components/WorkSpace.vue, ui/src/views/Dashboard.vue, ui/tests/integration/tests.spec.js
Updates workspace data when individuals are enrolled or withdrawn from an organization and when identities are split. Fixes #616
=> [ui] Fix outdated workspace data

ui/src/components/IndividualEntry.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Shows the unlock icon when you hover over a locked individual on the table. Closes #642.
=> [ui] Show unlock icon on hover

ui/src/components/EnrollModal.vue, ui/src/components/IndividualsTable.stories.js, ui/src/components/IndividualsTable.vue, ui/src/components/OrganizationSelector.stories.js, ui/src/components/OrganizationSelector.vue, ui/src/components/ProfileModal.stories.js, ui/src/components/ProfileModal.vue, ui/src/components/WorkSpace.stories.js, ui/src/views/Dashboard.vue, ui/src/views/Individual.vue, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/mutations.spec.js, ui/tests/unit/queries.spec.js
Adds the `OrganizationsSelector` component to choose from a list of organizations and replaces the current simple inputs with that component (the one introduced in #630 would still need to be replaced).
Closes #639.
=> [ui] Organization choices in the forms to assign organizations

ui/src/components/ExpandedIndividual.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
Removes the "Profile" section for the expanded individuals on the table. Fixes #633.
=> [ui] Remove profile data from the Individuals table

ui/src/components/IndividualEntry.vue
Replaces `Delete profile` with `Delete individual` in the dropdown menu of each individual entry.
Fixes #631.
=> [ui] Replace 'Delete profile' with 'Delete individual'

poetry.lock, pyproject.toml, releases/unreleased/update-package-dependencies.yml
Update Jinja2 package and make dev-dependencies similar to other Grimoirelab packages
=> Update package dependencies

ui/src/apollo/fragments.js, ui/src/apollo/mutations.js, ui/src/apollo/queries.js, ui/src/components/Identity.vue, ui/src/components/IndividualsTable.stories.js, ui/src/components/IndividualsTable.vue, ui/src/components/Recommendation.stories.js, ui/src/components/Recommendations.vue, ui/src/components/WorkSpace.stories.js, ui/src/utils/actions.js, ui/src/views/Dashboard.vue, ui/src/views/Individual.vue, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap
This PR updates the `Recommendations` component and the `Individuals` view to work with the queries and mutations from #673.
=> [ui] Show merge recommendations

.github/workflows/tests.yml, ui/package.json, ui/yarn.lock
Removes all Storybook packages and the GitHub action test that uses Storybook snapshots.
=> [ui] Remove Storybook

config/settings/devel.py, config/settings/testing.py, sortinghat/config/settings.py, sortinghat/core/middleware.py
Fix allow_any function from django-graphene-jwt.
Solution from https://stackoverflow.com/a/71296685
=> [middleware] Fix 'NoneType' object has no attribute 'fields'

ui/.storybook/main.js, ui/package.json, ui/src/components/IndividualCard.stories.js, ui/yarn.lock
Adds Storybook as a dev dependency.
=> [ui] Install Storybook

ui/src/router/index.js
Fixes the issues with the individuals profile page not loading and the URL appending "/login" every time the page is refreshed
=> [ui] Fix routing issues

README.md
This PR updates the way the UI is compiled after changing the production path to `/identities`
=> [docs] Update documentation for using SortingHat

releases/unreleased/set-top-domain-from-ui.yml, ui/src/apollo/mutations.js, ui/src/apollo/queries.js, ui/src/components/OrganizationModal.vue, ui/src/components/OrganizationsTable.vue, ui/src/views/Dashboard.vue
Adds the option to mark domains as top domains on the Organization's modal.
Fixes #729.
=> [ui] Set domain as top domain

ui/yarn.lock
Upgrades Webpack 5 version to fix a security issue.
=> Upgrade Webpack to version 5.77.0

ui/tests/e2e/support/index.js
Fixes the lint warnings on the end to end tests.
=> [ui] Fix lint warnings

releases/unreleased/remove-groups-table-from-ui.yml, ui/src/apollo/queries.js, ui/src/components/OrganizationEntry.vue, ui/src/components/OrganizationsTable.vue, ui/src/views/Dashboard.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
This PR removes the groups table from the dashboard and makes some small style changes to make the remaining tables more responsive.
=> [ui] Remove groups table

README.md, releases/unreleased/create-user-command.yml, sortinghat/server/sortinghat_admin.py
This PR allows the creation of new accounts using Django commands. To make a new account use the following:
```
Usage: sortinghat-admin create-user [OPTIONS]
Create a new user given a username and password
Options:
--username TEXT   Specifies the login for the user.
--is-admin        Specifies if the user is superuser.
--no-interactive  Run the command in no interactive mode.
--help            Show this message and exit.
```
=> [cmd] Create new accounts using commands

releases/unreleased/drag-and-drop-to-enroll-in-teams.yml, ui/src/components/ExpandedIndividual.vue, ui/src/components/ExpandedOrganization.vue, ui/src/components/IndividualCard.vue, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.vue, ui/src/components/OrganizationEntry.vue, ui/src/components/OrganizationsTable.vue, ui/src/components/TeamEnrollModal.stories.js, ui/src/components/TeamEnrollModal.vue, ui/src/components/WorkSpace.vue, ui/src/mixins/enroll.js, ui/src/views/Dashboard.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
This PR moves the full list of teams from a modal to the expanded organization and allows individuals to be dragged and dropped into a team to affiliate them and viceversa.
=> [ui] Improve teams UI

pyproject.toml, releases/unreleased/static-not-included-in-wheel-package.yml
Include static files in Python package
=> Include static files in Python package

releases/unreleased/unreadable-large-numbers-in-pagination.yml, ui/src/styles/index.scss
Fixes the width of the buttons to make all page numbers fully visible.
Fixes #770.
=> [ui] Fix unreadable large numbers in pagination

releases/unreleased/recommendation-by-individual.yml, ui/src/apollo/mutations.js, ui/src/components/IndividualEntry.vue, ui/src/components/IndividualsTable.stories.js, ui/src/components/IndividualsTable.vue, ui/src/components/MatchesModal.stories.js, ui/src/components/MatchesModal.vue, ui/src/views/Dashboard.vue, ui/src/views/Individual.vue, ui/tests/unit/__snapshots__/mutations.spec.js.snap, ui/tests/unit/__snapshots__/queries.spec.js.snap, ui/tests/unit/__snapshots__/storybook.spec.js.snap, ui/tests/unit/mutations.spec.js, ui/tests/unit/queries.spec.js
This PR adds the ability to generate matching recommendations for an individual from the UI. The button on the individual's profile or on their drop down menu on the table open a modal where the matching criteria can be configured.
Closes #779.
=> [ui] Recommendations by individual

releases/unreleased/add-profile-to-workspace.yml, ui/src/store/index.js, ui/src/views/Individual.vue
This PR adds a button to save an individual to the workspace in the `Individual` view. Fixes #816.
=> [ui] Add button to save to workspace in individual's page

releases/unreleased/link-to-profile-in-individual-cards.yml, ui/src/components/IndividualCard.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
This PR adds a link to the individual's profile on the card's name. Fixes #837.
=> [ui] Add link to profile on individual card

README.md
The MariaDB and MySQL version dependencies have changed. There were some changes to make the file look better.
=> Update dependencies and style on README

README.md
This commit includes documentation about the changes in the latest version related to permission groups.
=> [readme] Permissions groups breaking change

releases/unreleased/duplicated-github-links.yml, ui/src/views/Individual.vue, ui/tests/unit/__snapshots__/individual.spec.js.snap, ui/tests/unit/individual.spec.js
This PR changes the Individual view to only render a link for the same GitHub profile once and adds tests to check for this case.
Fixes #912.
=> [ui] Fix duplicated GitHub links in individual's view

releases/unreleased/merge-organizations-when-adding-an-alias.yml, ui/src/apollo/mutations.js, ui/src/components/GenericModal.stories.js, ui/src/components/GenericModal.vue, ui/src/composables/useModal.js, ui/src/views/Organization.vue, ui/tests/unit/__snapshots__/storybook.spec.js.snap
This PR adds the option on the organization view, when adding a new alias that is an existing organization, to merge them. It also refactors the modal's code to simplify it and reduce code duplication.
Fixes #913.
=> [ui] Merge existing organizations from the organizations edit view

docker/server-entrypoint.sh, docker/worker-entrypoint.sh
The worker container was not loading the custom settings due to the environment variable was being replaced.
=> Updated the worker image to load custom settings.

releases/unreleased/improved-session-cookies-security.yml, sortinghat/config/settings.py, sortinghat/core/decorators.py, tests/test_schema.py, ui/src/App.vue, ui/src/main.js, ui/src/store/index.js, ui/tests/e2e/support/commands.js
This PR adds settings to include the `Secure` attribute in the session cookies and a cookie expiry date of 30 minutes of inactivity by default to increase security. It also changes the `user_passes_test` decorator to differentiate an authentication error from a lack of permissions. The UI redirects to the login page if it receives an authentication error because the session expired.
=> Improve session cookies security

releases/unreleased/django-static-files-configuration.yml, sortinghat/config/settings.py
Migrate staticfiles config from STATICFILES_STORAGE to STORAGES.
Update the links in the settings file with the current LTS version of Django.
=> Update SortingHat Django settings to 5.2
