sortinghat/matching/__init__.py
sortinghat/matching/username.py
tests/test_matcher_username.py

Implemented this matcher sto cover the use case in which we have usernames from GitHub and we use them to unify identities.

[matchers] Add Username matcher.

---

README.md
misc/grimoirelab2sh
setup.py
sortinghat/parsing/grimoirelab.py
tests/data/grimoirelab_invalid.yml
tests/data/grimoirelab_invalid_datetime.yml
tests/data/grimoirelab_invalid_email.yml
tests/data/grimoirelab_invalid_missing_accounts.yml
tests/data/grimoirelab_invalid_missing_organization_name.yml
tests/data/grimoirelab_invalid_missing_profile.yml
tests/data/grimoirelab_invalid_missing_profile_name_isbot.yml
tests/data/grimoirelab_invalid_structure.yml
tests/data/grimoirelab_orgs_invalid_domains_list_with_empty_value.yml
tests/data/grimoirelab_orgs_invalid_empty_domains.yml
tests/data/grimoirelab_orgs_invalid_key_with_no_value.yml
tests/data/grimoirelab_orgs_invalid_missing_key.yml
tests/data/grimoirelab_orgs_invalid_wrong_domains_type.yml
tests/data/grimoirelab_orgs_valid.yml
tests/data/grimoirelab_valid.yml
tests/test_parser_grimoirelab.py

Address changes in PR #81 from @sanacl proposed by @sduenas.
Moreover, it was necessary to add some changes:
- In `sortinghat/parsing/grimoirelab.py`: as functions `__compose_uuid` and `__first_email_username` have been removed, now the variable `uuid` has the value of an incremental counter (`yid_counter`)
- In `tests/test_parser_grimoirelab.py`, when a `InvalidFormatError` exception raises, now it is used `assertRaisesRegex` function, which needs as a second parameter a regular expression for checking the exception message. 
- There was a wrong test, `data/grimoirelab_invalid_email.yml`. This was not checked in `sortinghat/parsing/grimoirelab.py` and the yml was bad formed also, so the exception never raised. Now there is a call to the function `__validate_email` and the yml has been …

[parsing:grimoirelab] Script, library and tests to parse GrimoireLab files (v2)

---

sortinghat/cmd/load.py
tests/test_cmd_load.py

So far, profile information was set only the first time a unique
identity was loaded. With this change, it will be updated only
when the given profile is not empty.
It fixes #90

[cmd:load] Update profile information when loading identities

---

setup.py

During Sorting Hat installation, the scripts stored under 'misc'
folder will be installed in the system.

Install misc scripts

---

sortinghat/parsing/grimoirelab.py
tests/data/grimoirelab_valid.yml
tests/test_parser_grimoirelab.py

When 'Unknown' organization is found as an enrollment, it will
be removed from the parsed output.
PR related to #104 issue.

[parsing:grimoirelab] Remove `Unknown` enrollments while parsing

---

.travis.yml
setup.py
sortinghat/db/model.py

This patch sets the minimum versions of PyMySQL and sqlalchemy to 0.7.0 and 1.1.15, respectively.

[sortinghat] Upgrade package dependencies

---

sortinghat/db/database.py
sortinghat/db/model.py

In some random situations SortingHat tables appear with an invalid collation. This is related to a wrong generation of the DDL table statement by SqlAlchemy, which may randomly prepend the collation information (mysql_collate) to the charset one (mysql_charset), causing the former to be ignored. Changing mysql_charset to mysql_default_charset fixes the problem.
To ensure the effectiveness of the fix, a shell script, which creates n SortingHat dbs and checks the collation, is provided below.
```
#!/bin/bash
db_name=test_sorting_hat
user=root
pwd=root
output=/tmp/sorting_hat
loops=20
for (( i = 1 ; i <= ${loops} ; i += 1 )) ; do
sortinghat -u ${user} -p${pwd} --host localhost --port 3306 -d ${db_name} init ${db_name}
mysql -u ${user} -p${pwd} ${db_name} -e "show create table identities;" > …
```

[db] Fix tables created with invalid collation

---

misc/grimoirelab2sh
sortinghat/parsing/grimoirelab.py
tests/test_parser_grimoirelab.py

When email_validation is set to False, invalid email addresses
will not make the parser fail. By default, email validation
is active.
Fixes #107

Set option to ignore invalid email addresses

---

sortinghat/cmd/init.py
sortinghat/db/database.py
sortinghat/exceptions.py
tests/test_api.py
tests/test_cmd_init.py
tests/test_exceptions.py

Really, for raising a new exception when intending to create a new database (using init). And a new option to Init, reuse, that will not trigger printing the message about "error creating database" which appears now every time you call Init.

[init] Add option for reusing database

---

sortinghat/cmd/load.py
tests/test_api.py
tests/test_cmd_load.py

Some information about the details of the identities being loaded were overbloating some logs. It seems that that this can be easily avoided using a flag designed for this. This patch uses it.
Also, fix one of the tests that didn't run in some circumstances.

[load] Avoid some messages when not in verbose mode

---

misc/gitdm2sh
sortinghat/parsing/gitdm.py
tests/data/gitdm_email_to_employer_invalid.txt
tests/test_parser_gitdm.py

This PR targets issue #119 . In a nutshell, when email_validation is set to False, invalid email addresses will not make the parser fail. By default, email validation is active.

[gitdm2sh] Set option to ignore invalid email addresses

---

setup.py

In fact, make it a "more than" dependency, instead of "exactly". Otherwise, other packages also depending on Pandas cannot be installed in the same environment.

[setup] Update pandas

---

sortinghat/api.py
tests/test_api.py

Some tests are not deterministic due to how results are ordered
after having searched them.

[tests] Fix non-deterministic tests

---

sortinghat/cmd/autogender.py

Help message for '--all' option was wrong.

[cmd:autogender] Fix typo in help output

---

sortinghat/api.py
tests/test_api.py

Method slice() was applied to the subquery that filters the identities and not to the whole query. This caused the number of unique identities returned were wrong.

[api] Fix error using SQL limit in search_unique_identities_slice()

---

sortinghat/parsing/sh.py
tests/data/sortinghat_valid_no_gender.json
tests/test_parser_sh.py

To support compatibilty between versions, gender data is not required anymore while parsing SH files.

[parsing:sh] Make gender profile info not required

---

.travis.yml
README.md
setup.py
tests/base.py
tests/test_cmd_config.py
tests/test_cmd_export.py
tests/test_cmd_init.py
tests/test_cmd_load.py
tests/test_model.py
tests/test_parser_eclipse.py
tests/test_parser_gitdm.py
tests/test_parser_grimoirelab.py
tests/test_parser_mailmap.py
tests/test_parser_mozilla.py
tests/test_parser_sh.py
tests/test_parser_stackalytics.py
tests/tests.conf.sample

In the migration to get all of GrimoireLab modules to run the tests via setup.py, some stuff waas needed, which is in this patch:
* Adaption of setup.py itself, including testing dependencies, adapting some other details in the script.
* Adaption of tests to be run from the parent directory.
* Create the database to use for testing, and remove it after the tests.
* New option in tests.conf, for running that code to create the database or not.
* Adapt the README.md to show how tests are run.
* Adapt .travis.yml to run with setup.py (and update it a bit).
In the process for adapting the tests to be run from the parent directory, their portability was increased: now they should run also in systems where "/" is not the path separator.

[tests] Adapt tests to run with setup.py test

---

README.md
setup.py
sortinghat/db/database.py

SQLAlchemy offers a pessimistic mode to handle database disconnection. Setting 'pool_pre_ping' parameter on the database engine will check if the database connection is still active when a session of the connection pool is reused. To check that it runs a simple SQL statement. This causes a small hit in the performance but it's worth it.
This feature was included in 1.2 version, so the list of dependencies has been updated as well.

[db] Handle disconnection using pessimistic mode

---

sortinghat/api.py
tests/test_api.py

When two identities were merged some enrollments were lost because the list of enrollments changes when these are moved from one identity to another. Making a in-place copy of the list using slices fixes the problem.

[api] Fix lost enrollments error merging identities

---

README.md
sortinghat/db/database.py
sortinghat/db/model.py
tests/test_api.py

The default charset of UTF-8 (utf8) in MySQL/MariaDB does not support, even when they are part of the standard, 4-bytes long characters. This means characters like emojis or certain chinese characters cannot be inserted. Usually, identities names or usernames have these types of characters.
The charset that fully supports UTF-8 is 'utf8mb4' using the collation 'utf8mb4_unicode_520_ci'. This collation implements the suggested Unicode Collation Algorithm (v5.2).
Using 'utf8mb4' also implies that the maximum size of char (VARCHAR and so on) columns is 191. Indexes cannot be larger than that when using InnoDB engine.
This patch can break the database so it is recommended to regenerate again the database from a dump.
More info:
* https://dev.mysql.com/worklog/task/?id=2673
* …

[db] Support UTF-8 fully in MySQL/MariaDB

---

sortinghat/api.py
tests/test_api.py

This code refactors and optimize how the last modified identities are retrieve to reduce the memory usage. First, the method `search_last_modified_identities` is splitted in two methods, one retrieves the last modified unique identities and the other one the last modified identities. Second, instead of retrieving the complete objects representing the identities, only their ids/uudis are returned.

[api] Optimize how last modified identities are retrieved

---

sortinghat/cmd/autoprofile.py
tests/test_cmd_autoprofile.py

When there are email address in 'name' or 'username' identity fields is possible that name profile will be set to this value.This can cause privacy issues in some contexts. For this reason, autoprofile will not set email values in this field.

[cmd:autoprofile] Avoid to set email addresses in name profile

---

sortinghat/cmd/autoprofile.py
tests/test_cmd_autoprofile.py

This error was caused when name or username fields were set to `None`. In these cases, the regular expression to match whether any of these values is an email address failed. A string value is required and not a None value.
Fixes #170

[cmd:autoprofile] Fix expected string or bytes-like object error

---

config/schema.py
config/settings/testing.py
sortinghat/core/db.py
sortinghat/core/errors.py
sortinghat/core/schema.py
tests/test_db.py
tests/test_errors.py
tests/test_schema.py

This PR addresses the requirements defined in #173. It adds four mutations:
* `addOrganization`
* `addDomain`
* `removeOrganization`
* `removeDomain`
Basic model operations have been defined to add/remove these object models too. It follows the schema defined by the stable version of SortingHat.

Mutations to add/remove organizations and domains

---

config/settings/testing.py
sortinghat/core/api.py
sortinghat/core/db.py
sortinghat/core/errors.py
sortinghat/core/schema.py
sortinghat/core/utils.py
tests/test_api.py
tests/test_db.py
tests/test_errors.py
tests/test_schema.py
tests/test_utils.py

The mutation `addIdentity` allows to add a new identity to the registry. These identities can be added to
an existing unique identity. By default, a new unique identity will be created which each new identity.
Along with this mutation, a set of functions have been ported from the previous version of SortingHat, like the generator of **UUIDs**, useful exceptions or the API handlers to add identities in an atomic transaction.
This PR addresses the requirements of #178 .

Define mutation to add identities

---

sortinghat/core/api.py
sortinghat/core/db.py
sortinghat/core/schema.py
tests/test_api.py
tests/test_db.py
tests/test_schema.py

The mutation `deletedentity` allows to remove identities and unique identities from the registry.
This PR addresses the requirements of #179 .

Define mutation to remove identities

---

sortinghat/core/api.py
sortinghat/core/db.py
sortinghat/core/schema.py
tests/test_api.py
tests/test_db.py
tests/test_schema.py

This mutation allows to update profile identities. Some functions were added to the API to update profiles in the database layer.
This commit adds the features requested on #184

Add GraphQL mutation to edit/update profiles

---

sortinghat/core/schema.py
tests/test_schema.py

With this commit, mutations produce the same types in the results. They return either the UUID of the update unique identity or identity and, the updated unique identity object.

Consolidate mutations results

---

sortinghat/core/schema.py
tests/test_schema.py

In order to get one uidentity by its uuid we added a filter to the
query. Moreover, a new type for filtering has been created in
order to add filters easily without changing the query, so we can
filter in more than one field using this new type.
This query expects these three behaviors:
- If you specify the uuid in the filter you will receive the
uidentites that match that uuid.
- If you don't put the uuid filter, you will receive all the
uidentites.
- If you put an uuid in the filter that does not exist,
you will receive an empty list.
There are also tests in order to check that it works as expected.

[graphql] Allow filtering uidentities by uuid

---

requirements.txt
sortinghat/core/api.py
sortinghat/core/db.py
sortinghat/core/models.py
sortinghat/core/schema.py
sortinghat/core/utils.py
tests/test_api.py
tests/test_db.py
tests/test_schema.py
tests/test_utils.py

This mutation allows to enroll identities in organizations. Some functions were added to the API to support this feature.
This commit adds the features requested on #185

Add GraphQL mutation to enroll identities

---

sortinghat/core/api.py
sortinghat/core/schema.py
tests/test_api.py
tests/test_schema.py

This mutation allows to withdraw identities from organizations. This commit adds the features requested on #186

Add GraphQL mutation to withdraw identities

---

tests/test_api.py

This test was missing in the PR that added this functionality. It tests whether the last date of modification for a unique identity is updated when withdraw() function is called.

[tests] Check whether last_modified field is updated in withdraw() call

---

sortinghat/core/api.py
sortinghat/core/db.py
sortinghat/core/schema.py
tests/test_api.py
tests/test_db.py
tests/test_schema.py

This PR add the functionality to move identities from one unique identity to another. This functionality works the same than in the original version of SortingHat. It also adds the features requested on #187.

Add GraphQL mutation to move identities

---

sortinghat/parsing/grimoirelab.py

This code fixes the warning YAMLLoadWarning thrown when calling yaml.load() without Loader. It fixes https://github.com/chaoss/grimoirelab-sortinghat/issues/199

[parsing] Fix YAMLLoadWarning for grimoirelab parser

---

README.md

I've made a few small text changes in the README to smooth out the language and wording of select sentences.
I also corrected a typo in the $PYTHONPATH variable name on line 93

Update languages and typos in the README

---

misc/grimoirelab2sh
sortinghat/parsing/grimoirelab.py
tests/data/grimoirelab_invalid_blacklist_empty_entry.yml
tests/data/grimoirelab_invalid_blacklist_no_list.yml
tests/test_parser_grimoirelab.py

While SortingHat standard file includes a list of blacklisted entries, GrimoireLab format does not.
This patch allows to include a blacklist on the YAML file, that will be parsed and converted into the
SortingHat format. Take into account the inclusion of a blacklist is totally optional.
This patch also updates `grimoirelab2sh` script to support this new feature.

Add support to parse a blacklist

---

setup.py

This code changes the version of the Pandas dependency to 0.22.0. This change is needed since in Travis the max version distribution for Pandas is currently 0.22.0. No problems appear when executing the Travis CI for sortinghat with a higher version (0.24.2), since the latter version is downloaded and compiled. This doesn't happen when executing Travis tests for components that have a dependency with
SortingHat (i.e., ELK and Mordred). In this case, Travis relies on the version distributions available
(<= 0.22.0).

[setup] Set pandas dep version to 0.22.0

---

sortinghat/core/api.py
sortinghat/core/schema.py
tests/test_api.py
tests/test_schema.py

This PR adds the functionality to merge two unique identities, including their identities, enrollments and profiles. 
This functionality works the same than in the original version of SortingHat **with one exception**: in the original version this method did nothing when `fromUuid` and `toUuid` were equal. Now, when this happens it returns an error.

Add GraphQL mutation to merge identities

---

sortinghat/core/api.py
sortinghat/core/db.py
sortinghat/core/schema.py
tests/test_api.py
tests/test_db.py
tests/test_schema.py

* Following the logic from other similar methods, there is a new method in `db.py` named `find_domain`, to obtain a domain object from the database using the domain name as a search term.
* New API methods: `add_domain` and `delete_domain`.
* `addDomain` and `deleteDomain` mutations now use these new API methods instead of the DB methods used directly.

Add API methods for adding and removing domains

---

sortinghat/core/db.py
tests/test_api.py
tests/test_db.py

This operation should not be logged as there is no dedicated method in `db.py` for adding a profile, but only for updating it.
Both `test_db.py` and `test_api.py` have been updated with this change.

[db] Do not log 'add_profile' operation when adding an identity

---

sortinghat/core/models.py
sortinghat/core/schema.py
tests/test_schema.py

These new queries allow to export the list of transactions and operations from the database with the following format:
```
query {
transactions {
name
createdAt
tuid
isClosed
closedAt
}
}
```
```
query {
operations {
ouid
opType
entityType
target
timestamp
args
trx {
name
createdAt
}
}
}
```
Both queries support filtering for most of the fields from their corresponding models, including `from_date` and `to_date` filters for both models (referencing to `created_at` field for transactions and `timestamp` for operations). This date can be passed as filter as a string following ISO 8601 format.
As the `args` field from `Operations` model is encoded in a serialized JSON, it was necessary to define a explicit conversion to return these encoded JSON fields as dictionaries. The class in charge of …

[schema] Add queries for exporting transactions and operations

---

tests/test_cmd_init.py

This code addresses #226, thus it fixes the tests `test_connection_error` in the classes `TestInitialize` and `TestInitCommand` by replacing the hard-coded params `host` and `port` with the ones defined in the tests.conf file.

[tests] Remove hard-coded DB params

---

sortinghat/core/schema.py
tests/test_schema.py

Following the filtering format from other fields, now the query asking for organizations supports an optional filter for the field `name`. 
Example:
```
{
organizations (
filters:{
name: "Example"
}
){
entities {
name
domains {
domain
isTopDomain
}
}
}
}
```

[schema] Add filtering by name to organizations query

---

setup.py

If we pin pandas at 0.22.0, it doesn't build with Python 3.7.x, apparently because of problems when building numpy for pandas.
Letting pandas be greater or equal than 0.22.0 doesn't seem to break anything, since platforms having only 0.22.0, as Travis had in July'19 (see #206), would still fulfill the dependency.
Signed-off-by: Jesus M. Gonzalez-Barahona <jgb@gsyc.es>

[setup] Let pandas be >= 0.22.0

---

config/schema.py
requirements.txt
sortinghat/core/decorators.py
sortinghat/core/schema.py
tests/test_schema.py

This PR is related with issue #233.
These changes add support for performing authenticated queries (both GraphQL queries and mutations), based on JSON Web Tokens (JWT).
To perform an authenticated query, an existing user must generate a token which has to be included in the `Authorization` header with the HTTP request. This token is generated using a mutation which comes defined by the `graphene-jwt` module, together with other extra mutations for verifying an existing token and refreshing it in case the token expired.
By default, all the queries and mutations now require authentication. This is controlled by a decorator named `check_auth` which comes from a pre-defined decorator named `login_required` and extending it to check both if the `user` from the `context.info` Django object is …

[schema] Add support for authenticated queries

---

sortinghat/core/api.py
sortinghat/core/schema.py
tests/test_api.py
tests/test_schema.py

The `merge_identities` mutation has been modified to accept a list of unique identities in the `from_uuid` field (now renamed to `from_uuids`). 
The API method for merging identities has been adapted to support this list as an input. New sub-methods have been included, iterating over the set of unique identities to merge.
Note: This PR is related to issue #236 .

[muggle] Add support for merging multiple identities at once

---

sortinghat/core/api.py
tests/test_api.py
tests/test_schema.py

Before this change, when a new unique identity was added by using the API method `add_identity`, it may receive some optional input parameters such as the name, the email and the source. This
information was set to the main sub-identity, but it was not propagated to the unique identity's profile, which remained empty.
After this change, the profile fields `name` and `email` are set with the corresponding input values from `add_identity` method.
This change affects both to `add_identity` and `move_identity` API methods, which are the ones where new unique identities are created.
Note: This PR is related with issue https://github.com/chaoss/grimoirelab-sortinghat/issues/245.

Fill profile information when a unique identity is created

---

sortinghat/db/model.py
tests/test_model.py

This code fixes the bug #121, thus it removes the type CoerceToBool (introduced at 5f69ed8), which was used to handle string representations of boolean values (i.e., True and False) for SqlAlchemy versions prior to 1.1.14. This was due to the fact that SqlAlchemy versions 1.1.x defined the Boolean type as follows:
```
Boolean typically uses BOOLEAN or SMALLINT on the DDL side,
and on the Python side deals in True or False.
```
Thus, equivalent string representations weren't handled and required the definition of the CoerceToBool (which created an additional CHECK constraint).
From versions greater than >=1.2.0 (already set in the current setup.py),
the CoerceToBool isn't needed anymore and can be removed. In particular, the
Boolean type is now defined as:
```
The Boolean datatype …
```

[db-model] Remove CoerceToBool type

---

sortinghat/core/api.py
sortinghat/core/schema.py
tests/test_api.py
tests/test_schema.py

This method accepts a list of identities as input, so multiple identities can be unmerged/splitted at once, creating a unique identity for each one. 
`name` and `email` fields from every identity will be set to the corresponding profile fields when the new unique identity is created. Nor the enrollments or the profile from any parent unique identity of the input identities are modified.
When a given identity `uuid` is equal to the `uuid` from its parent unique identity, there will be no effect.
Note: This PR is related to issue #237.

Add support for unmerging multiple identities at once

---

requirements.txt
setup.py
sortinghat/cli/client/__init__.py
sortinghat/cli/client/client.py
sortinghat/cli/client/schema.py
tests/test_client.py

This commit adds a naive implementation of a SortingHat client. It allows to run any query or mutation supported by the server calling the method `execute()`.
This client uses `sgqlc` library that allows to define GraphQL operations faster.
Related to #239.

First implementation of a basic client

---

sortinghat/cli/cmds/add.py
sortinghat/cli/sortinghat.py
sortinghat/cli/templates/add.tmpl
tests/cli/test_cmd_add.py

This command allows to create new identities in the registry.
The main differences between this and the original command is that it doesn't support matching nor merging of identities because this is not already supported.
This PR fixes #256

[client:add] Add command to add identities

---

sortinghat/cli/cmds/rm.py
sortinghat/cli/sortinghat.py
sortinghat/cli/templates/rm.tmpl
tests/cli/test_cmd_rm.py

The command 'rm' allows to remove unique identities or identities from the registry.
The differences with the original command are that the flag `identity ` has been removed. When the `uuid` references to a unique identity and to an identity it will remove both. The server doesn't allow to remove only the identity.
Fixes #257

[client:rm] Add command to remove identities

---

sortinghat/cli/cmds/mv.py
sortinghat/core/api.py
tests/test_api.py
tests/test_schema.py

This PR aims so solve issue #265. 
Before this change, two problematic cases were found:
* When `from_id` was the only identity of a UniqueIdentity, move operation made the unique identity got orphan.
* When `from_id` matched the `uuid` of its parent UniqueIndentity, the sub-identity was moved to a different UniqueIdentity (the one in `to_uuid`).
This fix prevents these cases to happen checking if `from_id` matches the `uuid` of its parent UniqueIdentity.
There was some existing tests which have been corrected after this change and a new test for this fix both for API and Schema.

[api] Fix move when from identity matches its unique identity

---

sortinghat/cli/cmds/enroll.py
sortinghat/cli/sortinghat.py
tests/cli/test_cmd_enroll.py

The command 'enroll' allows to create enrollments of unique identities in organizations.
The main difference with the original command is that it merges ranges of enrollments always, so the option `--merge` is not available anymore.
Fixes #259

[client:enroll] Add command to enroll identities to organizations

---

sortinghat/cli/cmds/withdraw.py
sortinghat/cli/sortinghat.py
tests/cli/test_cmd_withdraw.py

The new command 'withdraw' allows to remove enrollments from identities and organizations.
Fixes #260.

[client:withdraw] Add command to withdraw enrollments

---

sortinghat/cli/cmds/merge.py
sortinghat/cli/sortinghat.py
tests/cli/test_cmd_merge.py

The command 'merge' allows to merge a set of identities into another.
The difference with the original command is that it allows to merge a list of identities while the original  command only allowed one.
Fixes #262

[client:merge] Add command to merge identities

---

sortinghat/cli/cmds/split.py
sortinghat/cli/sortinghat.py
sortinghat/cli/templates/split.tmpl
tests/cli/test_cmd_split.py

The new command 'split' unmerges a set of identities.
Fixes #274 .

[client:split] Add command to unmerge identities

---

sortinghat/cli/cmds/lock.py
sortinghat/cli/sortinghat.py
sortinghat/cli/templates/lock.tmpl
tests/cli/test_cmd_lock.py

The command 'lock' implements two subcommands: 'add' to lock a unique identity; 'rm' to unlock it.
Fixes #275

[client:lock] Add a command to lock and unlock identities

---

sortinghat/cli/cmds/show.py
sortinghat/cli/sortinghat.py
sortinghat/cli/templates/show.tmpl
tests/cli/test_cmd_show.py

The command 'show' prints to the standard output information about the unique identities on the
registry.
The main difference with the original command is that `term` argument is not available yet because the server does not support to filter by it.
Fixes #276

[client:show] Add command to display info about unique identities

---

requirements.txt
sortinghat/cli/client/schema.py
sortinghat/cli/cmds/countries.py
sortinghat/cli/sortinghat.py
sortinghat/cli/templates/countries.tmpl
sortinghat/core/fixtures/countries.json
sortinghat/core/schema.py
tests/cli/test_cmd_countries.py
tests/test_schema.py

This PR adds three functionalities. First, it adds the list of countries that we have in the master branch. This list has been added as a fixture. Therefore, when the database is created, the list of countries can be imported using the command:
```
$ manage.py loaddata --settings <filename> countries.json
```
Second, it adds the GraphQL query `countries` to fetch the list of countries stored on the system.
Finally, the command `countries` has been also added to the client to display this list. This command allows to filter countries using the options `--code` and `--term`.
Fixes #285

Add countries support

---

sortinghat/cli/client/schema.py
sortinghat/cli/cmds/lock.py
sortinghat/cli/cmds/merge.py
sortinghat/core/api.py
sortinghat/core/schema.py
tests/cli/test_cmd_lock.py
tests/cli/test_cmd_merge.py
tests/test_api.py
tests/test_schema.py

This PR renames the mutations that make reference to identities. It renames `mergeIdentities` to `merge` and, `lockIdentity` and `unlockIdentity` to `lock` and `unlock.
This PR is related to #286.

Rename mutations referencing identities

---

config/settings/testing.py
requirements.txt
sortinghat/core/context.py
sortinghat/core/errors.py
sortinghat/core/jobs.py
sortinghat/core/log.py
sortinghat/core/recommendations/__init__.py
sortinghat/core/recommendations/affiliation.py
sortinghat/core/recommendations/engine.py
sortinghat/core/schema.py
tests/rec/test_affiliations.py
tests/rec/test_engine.py
tests/test_errors.py
tests/test_jobs.py
tests/test_log.py
tests/test_schema.py

This PR addresses the request in #292 adding several features to the branch. I was tempted to split them into different PRs but I don't think it makes sense because they need to work as a whole.
* **Recommendations system engine**, which allows to generate recommendations based on the data stored in the registry. The only recommendation type available now is `affiliations`.
* **Affiliation recommender**, which  generates a list of which organizations can be enrolled to which individuals.
* **Job manager**, to schedule and execute long-running jobs, such as recommendations or affiliation, in the asynchronously.
* **Affiliation job**, which runs the affiliation process based in a series of recommendations
* **Mutation to affiliate**, which allows to schedule an affiliation job
* **Mutation …

Affiliation job

---

ui/src/components/Identity.vue
ui/src/components/Indentity.stories.js
ui/src/components/IndividualCard.vue
ui/src/components/ProfileCard.stories.js
ui/src/components/ProfileCard.vue

This PR adds two new components to visualize identities data: `Identity`, and `ProfileCard`. These two components allow to visualize data as was designed in #298.

Visualize indentities data

---

requirements.txt
setup.py

The numpy dependency is constrained to <= 1.18.3. This change is needed since from version 1.19.x the support for python 3.5 has been discontinued.
Refs:
- https://numpy.org/devdocs/release/1.19.0-notes.html#id1
- https://github.com/numpy/numpy/issues/16294

[deps] Constrain numpy version to <= 1.18.3

---

ui/src/apollo/queries.js
ui/tests/unit/queries.spec.js

This PR allows the getIndividuals query to use the pagination functionality, adding the next arguments:
- page: integer in order to ask the page (by default, 1)
- pageSize: integer in order to define the size of the query (by default, 10) 
Moreover, the query returns all the data related to the pagination (pageInfo).
This PR is related to #303

[ui] Support pagination arguments in getIndividuals query

---

requirements.txt
sortinghat/core/jobs.py
sortinghat/core/recommendations/engine.py
sortinghat/core/recommendations/matching.py
sortinghat/core/schema.py
tests/rec/test_engine.py
tests/rec/test_matches.py
tests/test_jobs.py
tests/test_schema.py

Recommend identity matches for a list of individuals.
Note: This PR is related to issue #302 .
This job generates a list of recommendations with the matching identities which the input individuals can be merged with, based on a list of criteria composed by email addresses, name and/or usernames of the individuals.
The function behind the scenes checks if any identity from each individual matches with a given set of target individuals. First, it filters by the fields from the criteria and then it groups the matches by identity. Then, these groups are turned into sets of matching identities found among all the input identities set.
Each recommendation contains the uuid of the individual provided in the input list and a list with the matching individuals or the matching identities if the …

Get matching identities recommendations from sets of individuals

---

ui/src/App.vue
ui/src/components/Indentity.stories.js
ui/tests/unit/queries.spec.js

This PR fixes the three Vue warnings that are raised when running the ui tests described on #314 .
Two of them were due to some variables not having been declared before being used or assigned a value, and one was caused by a failing query on App.vue that didn't have any error control.

Fix ui test warnings

---

ui/src/components/ProfileCard.vue
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR turns the `Organizations` and `Individuals` sections
in ProfileCard.vue into nested, expandable lists, and adds a
count to the 'Individuals' header as requested in #317

[ui] Individuals and Organizations sections in ProfileCard as nested list

---

ui/src/apollo/mutations.js
ui/src/apollo/queries.js
ui/src/components/IndividualCard.stories.js
ui/src/components/IndividualCard.vue
ui/src/components/IndividualsGrid.stories.js
ui/src/components/IndividualsGrid.vue
ui/src/components/ProfileCard.vue
ui/tests/unit/IndividualCard.spec.js
ui/tests/unit/__snapshots__/IndividualCard.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR adds the functionality of locking or unlocking
individuals by clicking on the lock icon on the `IndividualCard`
component requested in #322 .
Those mutations require the individual's `uuid` as an
argument, so it is added to `IndividualCard` as a prop and passed
from `IndividualsGrid` and `ProfileCard`.
If the mutation fails, a snackbar with the error message is
displayed on the bottom of the screen.

[ui] Allow to lock individuals

---

config/settings/devel.py
ui/package.json
ui/src/main.js

This commit fixes the error produced when the app do petitions to
the Django server and the CSRF cookie is not set. To solve this,
the code forces a GET to the Django server in order to retrieve
the CSRF token, then the token is added when the Apollo server
is configured.

[ui] Add CSRF token to the Apollo petitions

---

ui/src/components/IndividualEntry.stories.js
ui/src/components/IndividualEntry.vue
ui/tests/unit/__snapshots__/storybook.spec.js.snap

Adds the `IndividualEntry` component, which displays a table row with an individual's name, organization, email and sources. The information can be expanded, but the slot for the expanded content must be implemented inside the parent `<v-table>` component and not this one. I mocked the behaviour in the Storybook story, placing `IndividualEntry` inside a table and adding the expanded content there.

[ui] Implement IndividualEntry component

---

ui/src/App.vue
ui/src/apollo/mutations.js
ui/src/components/ExpandedIndividual.stories.js
ui/src/components/ExpandedIndividual.vue
ui/src/components/IndividualCard.vue
ui/src/components/IndividualsTable.stories.js
ui/src/components/IndividualsTable.vue
ui/src/components/WorkSpace.stories.js
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/mutations.spec.js
ui/tests/unit/queries.spec.js

An individual's identity can be unmerged by clicking a button on the `ExpandedIndividual` identities list. The split individual is then placed on the workspace.
A new Apollo mutation is implemented to split the identities.

[ui] Split identities on ExpandedIndividual

---

ui/src/apollo/mutations.js
ui/src/components/ExpandedIndividual.vue
ui/src/components/IndividualsTable.vue
ui/src/components/WorkSpace.vue

Stops highlighting an individual in the table when that individual has been removed from the workspace.
Fixes #373

[ui] Remove highlight when individual is not on the workspace

---

ui/src/App.vue
ui/src/apollo/mutations.js
ui/src/components/OrganizationModal.stories.js
ui/src/components/OrganizationModal.vue
ui/src/components/OrganizationsTable.stories.js
ui/src/components/OrganizationsTable.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/mutations.spec.js
ui/tests/unit/queries.spec.js

Implements the `OrganizationModal` component, which displays a form that allows an organization and its domains to be created. The component is embedded inside `OrganizationsTable` and opens when the "add" button is clicked, as requested in  #383 . Two new GraphQL mutations -`addOrganization` and `addDomain`- are added to save the changes in the database.

Add organizations from the UI 

---

ui/src/App.vue
ui/src/apollo/mutations.js
ui/src/components/OrganizationEntry.vue
ui/src/components/OrganizationModal.stories.js
ui/src/components/OrganizationModal.vue
ui/src/components/OrganizationsTable.stories.js
ui/src/components/OrganizationsTable.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/mutations.spec.js
ui/tests/unit/queries.spec.js

Adds an edit icon to `OrganizationEntry`, which opens the `OrganizationModal` component. `OrganizationTable` passes the organization information and a new `deleteDomain` Apollo mutation to the modal so that the domains can be edited.

Edit organizations from the UI

---

ui/src/components/ProfileModal.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap

All enrollments in `ProfileModal` can be deleted by clicking the trashcan button next to them, like the domains in `OrganizationModal`. The add organization button is placed below them.

[ui] Allow all organizations in ProfileModal to be removed

---

ui/src/App.vue
ui/src/apollo/queries.js
ui/src/components/IndividualsTable.stories.js
ui/src/components/IndividualsTable.vue
ui/src/components/WorkSpace.stories.js
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/queries.spec.js

This PR adds an input to `IndividualsTable` that allows the user to search individuals by term, and an optional filters argument to the `getPaginatedIndividuals` Apollo query. The query is not performed if the search term is shorter than 3 characters. The input can be cleared to return the full list of individuals.

Add search function to the Individuals table

---

sortinghat/core/schema.py
tests/test_schema.py

Before this change, the filter `uuid` from the Individuals query only worked when that `uuid` matched with the `mk` from the individual. Now, this `uuid` could be from any of its identities.
This PR is still WIP:

[schema] Allow query individuals by any of their UUIDs

---

ui/package.json
ui/src/App.vue
ui/src/apollo/mutations.js
ui/src/components/Dashboard.vue
ui/src/components/Login.vue
ui/src/main.js
ui/src/router/index.js
ui/src/store/index.js
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/mutations.spec.js
ui/yarn.lock

This PR implements a basic sign in/out functionality. It adds the `vue-router` dependency, which is the official Vue tool to manage routes, to to create the main `/` and `/login` routes and check if a user is authenticated before navigating to them.
The main view is moved to its own `Dashboard` component. A new `Login` component where a user can enter and submit credentials is displayed at the `/login` route. The user token is retrieved with the `tokenAuth` Apollo mutation and saved to a cookie and to the store, and it is used in the authorization header of the remaining Apollo queries and mutations.
The nav bar displays the user name when logged in. The user can click the username to log out, which removes the authentication cookies and redirects to the login view.

Design sign in/out method for the UI

---

requirements.txt
setup.py

SQLAlchemy 1.4.x doesn't work with the current code in SortingHat. This is a hotfix to force pip to install a version lower than 1.4.
Signed-off-by: Santiago Dueñas <sduenas@bitergia.com>

Limit SQLAlchemy versions to <1.4

---

sortinghat/core/errors.py
sortinghat/core/schema.py
tests/test_errors.py
tests/test_schema.py

Now, individuals can be queried filtering by their last updated date.
The accepted filter formats are controlled by regular expressions matching two patterns:
* A comparison operator (>, >=, <, <=) and a date (e.g. `>=YYYY-MM-DDTHH:MM:SSZ`).
* A range operator (..) between two dates (e.g. `YYYY-MM-DDTHH:MM:SSZ..YYYY-MM-DDTHH:MM:SSZ`)
The accepted date format is ISO 8601, `YYYY-MM-DDTHH:MM:SSZ`, also accepting microseconds and time zone offset (`YYYY-MM-DDTHH:MM:SS.ms+HH:HH`).
Note: This PR is linked to issue #394 .

[schema] Support filtering individuals by last updated date

---

ui/src/components/Dashboard.vue
ui/src/components/IndividualCard.vue
ui/src/components/IndividualEntry.vue
ui/src/components/IndividualsTable.vue
ui/src/components/OrganizationEntry.vue
ui/src/components/OrganizationsTable.vue
ui/src/components/WorkSpace.stories.js
ui/src/components/WorkSpace.vue
ui/src/mixins/enroll.js
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap

An organization can be dragged and dropped into an `IndividualCard` or an `IndividualEntry`. They recover the organization's name and pass it to their parent component, `IndividualsTable` or `Workspace`. The parent then uses the functions in `enrollMixin` to enroll the individual.

[ui] Drag and drop organizations to enroll individuals

---

ui/src/apollo/mutations.js
ui/src/components/Dashboard.vue
ui/src/components/WorkSpace.vue

Fixes #414. When individual cards were removed from the workspace, the list of individuals in the workspace that was saved in the dashboard was not updated. This made them reappear when an identity was split from an individual and its card was moved to the workspace.

[ui] Fix removed cards reappearing in workspace

---

ui/src/App.vue
ui/src/components/IndividualEntry.vue
ui/src/components/IndividualsTable.vue
ui/src/components/OrganizationEntry.vue
ui/src/components/OrganizationModal.vue
ui/src/components/OrganizationsTable.vue
ui/src/components/ProfileModal.vue
ui/src/components/WorkSpace.vue
ui/src/plugins/vuetify.js
ui/src/styles/index.scss
ui/src/views/Dashboard.vue

Sets the blue and yellow GrimoireLab colors as primary and secondary colors in the Vuetify theme and changes some styles.
Note: the JWT authentication plugin is having issues at the moment: https://github.com/flavors/django-graphql-jwt/issues/241
If you can't log in, you can remove `meta: { requiresAuth: true }` from `/ui/src/router/index.js` to access the dashboard.

[ui] Use GrimoireLab color scheme

---

ui/.storybook/preview.js
ui/src/components/ExpandedIndividual.vue
ui/src/components/ExpandedOrganization.vue
ui/src/components/IndividualsTable.vue
ui/src/styles/index.scss
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR attempts to improve the visual limits of expanded individuals to make the information more readable as requested in #423. It includes the color theme from #424.

Define visual limits in individuals table 

---

sortinghat/core/api.py
sortinghat/core/schema.py
tests/test_api.py
tests/test_schema.py

This mutation updates atomically an individual's enrollment or set of enrollments defined by the initial date range to a new date range.
As in the enroll method wider date ranges get merged into the wider one, this mutation and its corresponding API method uses the `withdraw` and the `enroll` API methods to ensure the dates are updated even in this case following these steps:
* Withdraw the enrollments from the provided organization and an existing date range.
* Set a new enrollment to that same organization with the new date range.
By default, the `force` parameter from the `enroll` method is also included and set to `True` by default, as it overwrites default dates in case a more specific date is provided.
In case any of the new dates are missing, the former value for that date will be …

Add mutation for updating enrollment dates

---

ui/src/apollo/mutations.js
ui/src/apollo/queries.js
ui/src/components/IndividualsTable.stories.js
ui/src/components/WorkSpace.stories.js
ui/src/utils/actions.js

Gets the individuals' main uuid, used when identities are moved or merged, from the `mk` field instead of from its first identity.

[ui] Get individuals uuid from 'mk' field

---

ui/src/views/Dashboard.vue

This PR makes the Individuals and Organizations containers fluid so the space between them is reduced and consistent in different screen sizes.

[ui] Reduce the space in between Individuals and Orgs tables

---

ui/src/components/IndividualEntry.vue
ui/src/components/IndividualsTable.vue

Expands an individual's information when double clicking an entry. The select event performed on click is delayed for some milliseconds to prevent it from getting triggered on double click.
Fixes #431.

[ui] Expand individual entry on double click

---

ui/src/components/WorkSpace.vue
ui/tests/unit/__snapshots__/storybook.spec.js.snap

Makes the empty Workspace have the same height as if it had a row of cards by default. Fixes #438.

[ui] Make Workspace height fixed

---

sortinghat/core/schema.py
tests/test_schema.py
ui/src/apollo/queries.js
ui/src/components/OrganizationsTable.vue
ui/src/views/Dashboard.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/queries.spec.js

The schema and UI are updated to allow filtering organizations by term:
- A `term` filter is added to the `organizations` query in `schema.py`, which returns a list of organizations whose name or domains contain the given term.
- Search filters are added to the `getPaginatedOrganizations` Apollo GraphQL query. The functions that call that query are updated accordingly.
- The `Search` component is imported in `OrganizationsTable`.

Search organizations by term

---

sortinghat/core/jobs.py
sortinghat/core/schema.py
tests/test_schema.py

This PR adds the `jobs` query, which returns a paginated list of all the jobs in the main queue.
The query has the following format:
```
query {
jobs(pageSize: Int, page: Int) {
entities {
jobId
status
jobType
errors
result
}
pageInfo {
page
pagesize
numPages
hasNext
hasPrev
totalResults
}
}
}
```

[schema] Add query to get the list of jobs

---

sortinghat/core/schema.py
tests/test_schema.py
ui/src/App.vue
ui/src/apollo/queries.js
ui/src/components/JobsTable.stories.js
ui/src/components/JobsTable.vue
ui/src/router/index.js
ui/src/views/Jobs.vue
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/queries.spec.js

Adds the `JobsTable` component, which displays a list of jobs, their type and their status, retrieved with the `getJobs` Apollo GraphQL query. The list can be accessed through the `/jobs` route. A link can be found on the app bar menu.

[ui] Visualize jobs

---

sortinghat/core/schema.py
tests/test_schema.py
ui/src/components/Search.vue
ui/src/views/SearchHelp.vue
ui/tests/unit/queries.spec.js
ui/tests/unit/search.spec.js

Adds the `isBot` filter to the individuals query, which accepts a boolean value and returns a list of individuals filtered by their bot status.

Search bot individuals

---

sortinghat/core/schema.py
tests/test_schema.py
ui/src/views/SearchHelp.vue
ui/tests/unit/queries.spec.js
ui/tests/unit/search.spec.js

Adds the `country` filter to the `individuals` query, which returns individuals with a given country name or country ISO codes.
In the UI `Search` component, the syntax is `country:"country name"`.

Search individuals by country

---

ui/src/components/ExpandedIndividual.vue
ui/src/components/IndividualEntry.vue
ui/src/components/IndividualsTable.vue
ui/src/components/OrganizationsTable.vue
ui/src/components/Search.stories.js
ui/src/components/Search.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap

Adds a checkbox that selects or deselects all individuals on `IndividualsTable` to perform batch operations. 
- Locked individuals can be selected, but they still can't be merged or deleted.
- The action buttons and search boxes on both individuals and organizations tables are moved to a new row to make space for it, so the search box doesn't need to be closed by default.
-  New buttons to split all identities and to remove all affiliations are also added to `ExpandedIndividuals`. They are disabled for locked individuals.
This is a preview of the changes:

[ui] Select all individuals for batch operations

---

ui/src/components/IndividualsTable.vue
ui/src/components/OrganizationsTable.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap

Adds an input to the `IndividualsTable` and `OrganizationsTable` footer where users can select how many items per page are shown.

[ui] Make table items per page editable

---

.github/workflows/ci.yml
config/settings/testing.py

This commit adds the github action ci workflow to the repository. This CI workflow is triggered whenever there is a push or pull_request event to the muggle branch. It runs the test suite of the backend app and the frontend app whenever the workflow is triggered.
The database configuration for the workflow is also updated.
Fixes https://github.com/chaoss/grimoirelab-sortinghat/issues/475.

[gha] Add CI workflow action

---

config/settings/devel.py
setup.cfg
setup.py
sortinghat/core/api.py
sortinghat/core/jobs.py
sortinghat/core/schema.py
tests/test_schema.py

This PR fixes the flake8 errors present in the muggle branch. This is necessary as a flake8 check must be added in the github action ci workflow.
It adds a configuration to ignore some errors of a file as it is hard to understand the logic if we format the file. It also adds a configuration to excludes a file.

[flake8] Fix flake8 errors

---

poetry.lock
pyproject.toml

This commit adds the files required to add poetry support to sortinghat muggle branch.
This update is required to start using the Bitergia/release-tools for automating the GrimoireLab toolset releases.
Fixes #462

[sortinghat] Add poetry support

---

.github/workflows/ci.yml
poetry.lock
pyproject.toml

This PR updates the workflow configuration to use poetry for the flake8 check and running the test suite whenever the action is triggered.
It also adds flake8 and httpretty as dev dependencies to the pyproject.toml file as these are needed for the workflow.
#462

[gha] Use poetry for the CI workflow

---

ui/.storybook/preview.js
ui/src/App.vue
ui/src/components/IndividualsTable.vue
ui/src/components/OrganizationModal.vue
ui/src/components/OrganizationsTable.vue
ui/src/components/ProfileModal.vue
ui/src/components/WorkSpace.vue
ui/src/main.js
ui/src/plugins/logger.js
ui/src/views/Login.vue
ui/tests/unit/logger.spec.js

Logs a message to the console when the following operations are performed, including the values that were changed:
- Add identity
- Move identity
- Update profile
- Enroll in organization
- Update enrollment
- Remove enrollment
- Merge identities
- Split identities
- Delete identity
- Add organization
- Add domain
- Remove domain
- Log in/out
The logs are not shown in production mode (when running `yarn serve --mode production`, for example).

[ui] Add logging messages

---

sortinghat/core/schema.py
tests/test_schema.py

When querying for a failed job, returns the error log from the `exec_info` attribute instead of from the empty `result`.
Fixes #487.

[schema] Return error when job has failed

---

sortinghat/cli/client/schema.py
sortinghat/core/schema.py

This parameter is not available anymore to remove individuals. Individuals or identities are removed when their uuid is given
when 'deleteIdentity' mutation is called.

[schema] Remove deprecated 'delete_individual' parameter

---

poetry.lock
pyproject.toml

The package "django-graphql-jwt" is incomatible with the latest version of PyJWT (2.0.1). This raises an error when the mutation "totenAuth" is called because django-graphql-jwt is calling PyJWT API incorrectly. This patch fixes the problem reported in #496.
Without this version the next mutation raised an error:
```
mutation tokenAuth {
tokenAuth(username:"root", password:"*******") {
token
}
}
```
```
"errors": [
{
"message": "'str' object has no attribute 'decode'",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"tokenAuth"
],
"extensions": {
"code": 128
}
}
],
"data": {
"tokenAuth": null
}
}
```
Now it returns something like:
```
{
"data": {
"tokenAuth": {
"token": "************************"
}
}
}
```

Pin PyJWT to 1.7.1 to fix incompatibility problem with django-graphql-jwt

---

sortinghat/core/log.py
tests/test_db.py
tests/test_log.py

This PR fixes some integrity issues that we have in the code. First, it fixes a bug which causes to overwrite log objects if the same id is used. Second, it adds a unit test to check if enrollments  with the same data can be inserted twice.

Fix integrity issues

---

sortinghat/parsing/gitdm.py
tests/data/gitdm_email_to_employer_invalid.txt
tests/data/gitdm_email_to_employer_valid.txt
tests/test_parser_gitdm.py

This change is needed to execute `gitdm2sh`:
- Skip the lines when there is no email.
- Accept one character as organization name.
Tests updated accordingly.

[parsing/gitdm] Update VALID_LINE_REGEX expression

---

sortinghat/core/models.py
tests/test_schema.py
ui/src/components/IndividualsTable.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/queries.spec.js

Allows the individuals to be sorted by their creation date, both from the API and from the UI.

Order individuals by createdAt field

---

sortinghat/core/jobs.py

Since Python 3.7 was introduced, `StopIteration` exceptions are raised directly when `next()` doesn't generate a new item. This
patch adds compatibility other Python versions catching this exception.

[jobs] Catch StopIteration for Python 3.7 compatibility

---

sortinghat/core/jobs.py

Adds a `check_criteria` function that raises a `ValueError` if the criteria selected for the `unify` or `recommend_matches` jobs is invalid. Fixes #491

[jobs] Raise ValueError for invalid criteria

---

sortinghat/core/models.py
tests/test_schema.py
ui/src/components/IndividualsTable.vue

Allows individuals to be sorted by their name, both from the API and from the UI.
Fixes #514.

Order individuals by profile name

---

sortinghat/core/schema.py
tests/test_schema.py
ui/src/components/Search.vue
ui/src/views/SearchHelp.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/search.spec.js

Adds the `enrollmentDate` filter, which allows individuals to be filtered by the dates of their enrollment in an organization.
The valid filter formats are:
- A comparison operator (>, >=, <, <=) and a date (e.g. `>=YYYY-MM-DDTHH:MM:SSZ`).
- A range operator (..) between two dates (e.g. `YYYY-MM-DDTHH:MM:SSZ..YYYY-MM-DDTHH:MM:SSZ`)
Fixes #520

Filter individuals by enrollment date

---

sortinghat/core/schema.py
tests/test_schema.py
ui/src/components/Search.vue
ui/src/views/SearchHelp.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap

This PR adds the `isEnrolled` filter to the `individuals` query, which returns a list of individuals that are affiliated or not to any organizations.

Filter individuals by whether or not they have any enrollments

---

ui/src/views/Dashboard.vue

Checks if there is a saved workspace before requesting its items when the dashboard is loaded, fixing the Vue console error mentioned in #534.

[ui] Fix console warning when workspace is empty

---

.github/workflows/ci.yml
README.md

The '-u' argument was needed to update the failing snapshots. It is not required anymore, this PR removes it.

Remove '-u' from the unit tests

---

.github/workflows/tests.yml
README.md

This PR renames the ci github actions workflow to avoid ambiguity. It also adds a rule to restrict the tests workflow to run when a release tag is pushed to the repository to avoid redundant workflows.
It also adds additional python versions 3.7, 3.8 for running the test suite.

[gha] Update tests workflow

---

README.md
utils/create_sh_0_7_fixture.py

This script creates a fixture JSON file given the old SortingHat (0.7.x)
database to load into the new SortingHat using Django.
Execute:
```
$ python3 create_fixture.py localhost test_sh
[2021-06-10 17:29:11,461][INFO] Start creating fixture file for test_sh
[2021-06-10 17:29:21,252][INFO] Fixture file created: test_sh_fixture.json
[2021-06-10 17:29:21,252][INFO] Total duration: test_sh_fixture.json
```
First, you have to create a new database.
```
mysql> CREATE DATABASE new_sh CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
```
Load fixture JSON file using Django
```
$ python3 manage.py loaddata test_sh_fixture.json --settings=config.settings.devel
Installed 148542 object(s) from 1 fixture(s)
```
Fixes #542

[utils/create_fixture] Create fixture JSON file of a database

---

config/settings/devel.py
config/settings/testing.py
sortinghat/core/jobs.py
sortinghat/core/recommendations/engine.py
sortinghat/core/recommendations/gender.py
sortinghat/core/schema.py
tests/rec/test_engine.py
tests/rec/test_gender.py
tests/test_jobs.py
tests/test_schema.py

This PR adds a `recommendGender` mutation, which returns a job with a possible gender for each given individual uuid based on their profile name. The recommendations are provided by the genderize.io API.
Example of the mutation:
```
mutation {
recommendGender(uuids: ["uuid"], apiToken: "token") {
jobId
}
}
```
Example of the job query:
```
query {
job(jobId: "id") {
jobId
status
jobType
result {
__typename
... on GenderRecommendationType {
uuid
gender
accuracy
}
}
errors
}
}
```
The individuals' genders can be autocompleted using these same recommendations with the `autogender` mutation.
Example of the mutation:
```
mutation {
autogender(uuids:["uuid1", "uuid2"], apiToken: "token") {
jobId
}
}
```
Example of the job result query:
```
query {
job(jobId: "id") {
status
jobType
result {
... …
```

Gender recommendations

---

ui/package.json
ui/src/main.js
ui/vue.config.js
ui/yarn.lock

The default API URL `/api/` can be overwritten with the `VUE_APP_API_URL` environment variable. It can be set on an .env file or passed as a command line argument when the UI is launched, eg. `yarn serve --api_url=http://localhost:8000/api/`
Closes #559.

[ui] Get GraphQL API URL from env variable

---

README.md
poetry.lock
pyproject.toml
sortinghat/server/sortinghat_admin.py

This tool allows to perform some admin related tasks such as, creating new super users or apply database migrations.
Install the code and run the operations with `setup` or `upgrade` commands.
```
$ sortinghat-admin --config=config.settings.devel setup
$ sortinghat-admin --config=config.settings.devel upgrade
```

Add admin command line tool

---

README.md
pyproject.toml
sortinghat/server/sortinghatw.py

The command added to this commit is a wrapper of the command 'rqworker'. Instead of running it with 'django-admin' or 'manage.py', we can use 'sortinghatw' to do it.

Add command 'sortinghatw' to run workers

---

sortinghat/core/api.py
tests/test_api.py

Previously, the delete_team method could not handle deleting teams
that do not belong to any organization. This change removes the
requirement for delete_team to have organization as a parameter.
Signed-off-by: Rashmi-K-A <k.a.rashmi04@gmail.com>

[api] Fix delete_team method

---

sortinghat/core/schema.py
tests/test_schema.py

This PR includes the changes for extending the GraphQL layer to manipulate Team objects. It adds a query for searching through Team objects and two mutations - `AddTeam` and `DeleteTeam` for creating and deleting Team objects respectively.
This PR closes #558.

[schema] Add GraphQL layer for teams

---

ui/src/components/IndividualsTable.vue
ui/src/components/ProfileModal.vue

With this PR, the information on the `Organizations` table is updated when an individual is enrolled or unenrolled from an organization.
Fixes #565.

[ui] Update organizations on enrollment change

---

sortinghat/core/jobs.py
sortinghat/core/recommendations/gender.py
sortinghat/core/schema.py
tests/rec/test_gender.py
tests/test_jobs.py
tests/test_schema.py

This PR implements the suggestions on issue #570, differentiating between strict and loose name matching and caching the recommendation results. By default, the name validation will check for name following a `Name Lastname` pattern, with any number of spaces between them, and for the name to be at least two characters long. This can be disabled with the `no_strict_matching` flag, which will only check that the name has a minimum of 2 characters.

[gender] Improve name patterns

---

sortinghat/core/schema.py
tests/test_schema.py

This commit adds the groups query to GraphQL.
The groups query allows users to query for unaffiliated
groups in the registry.
Signed-off-by: Rashmi-K-A <k.a.rashmi04@gmail.com>

[schema] Add query for groups

---

ui/src/apollo/mutations.js
ui/src/apollo/queries.js
ui/src/components/ExpandedOrganization.vue
ui/src/components/OrganizationsTable.stories.js
ui/src/components/OrganizationsTable.vue
ui/src/components/TeamModal.stories.js
ui/src/components/TeamModal.vue
ui/src/styles/index.scss
ui/src/views/Dashboard.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/mutations.spec.js
ui/tests/unit/queries.spec.js

This commit adds a modal component to the Organizations
table. On clicking the View teams button in the table,
this modal opens up displaying all the top level teams
of the organization.
Signed-off-by: Rashmi-K-A <k.a.rashmi04@gmail.com>

[ui] add TeamModal component

---

README.md
sortinghat/server/sortinghat_admin.py

With this patch, the command 'sortinghat-admin setup' creates an empty database before migrations and fixtures
are applied.
The new database will have the name of the variable 'NAME' under the default database settings.
This database will be only created if it doesn't exist.

[server] Create database during setup

---

sortinghat/app/urls.py

This PR replaces the empty `path` for the UI with a regular expression to capture Vue's routes.
Fixes #585 .

Handle Vue routes from Django urls

---

sortinghat/config/settings.py

This code allows connecting to a Redis with password.

[config/settings] Add RQ_QUEUES password parameter

---

requirements.txt
setup.py

Markup has release a new version and Jinja 2.11.3 throws an error.
Pin the version to <3.1.0 since from 3.1 the support for python 3.6 will be discontinued.
Related to https://github.com/chaoss/grimoirelab-sortinghat/issues/603

[deps] Update Jinja version

---

ui/src/apollo/mutations.js
ui/src/apollo/queries.js
ui/src/components/EnrollmentList.stories.js
ui/src/components/EnrollmentList.vue
ui/src/components/ExpandedIndividual.vue
ui/src/components/IndividualsTable.stories.js
ui/src/components/IndividualsTable.vue
ui/src/components/TeamEnrollModal.stories.js
ui/src/components/TeamEnrollModal.vue
ui/src/views/Dashboard.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/enrollmentList.spec.js

This PR updates the user interface to allow individuals to be enrolled in teams. 
Users can click on a button next to an individual's enrollment to add a team for that organization. This opens the `TeamEnrollModal`, which shows a form to enter the team name and optional dates.
The enrollments are grouped by organization, with the teams indented below their parent. There is also an icon next to their names to make it clearer if it is an organization or a team.
The template and logic to show an individual's enrollments is moved to a new component `EnrollmentList` to prevent `ExpandedIndividual` from becoming too complex.
The mutations to withdraw and update the enrollment dates are also updated to account for teams.

[ui] Enroll individuals in teams

---

requirements.txt
setup.py

This PR updates the version of numpy to <1.21.0 in requirements.txt file and setup.py.

Bump numpy to 1.21.0

---

ui/src/views/Dashboard.vue

This PR fixes #617. When you click an organization to see the list of enrolled individuals, it clears the previous enrollment filter and waits for Vue to update it before setting the new one.

[ui] Fix filtering individuals by organization

---

ui/src/components/DateInput.vue
ui/src/components/ProfileModal.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/dateInput.spec.js

This PR replaces the date pickers in `ProfileModal` with the `DateInput` component, which allows the user to type a date. The component is also improved:
- Sets the date for the Vuetify picker in a YYYY-MM-DD format. This was preventing the date picker from highlighting the chosen date.
- Adds a help text with the right date format.
- Adds validation rules used by `ProfileModal`.
- Adds a `single-line` prop to match the input style in the modal.
Fixes #618.

[ui] Improve date inputs

---

sortinghat/core/schema.py
ui/src/apollo/queries.js
ui/src/components/OrganizationsTable.stories.js
ui/src/components/OrganizationsTable.vue

This PR fixes the `enrollment`, `isEnrolled` and `source` filters returning duplicates in the individuals query.
It also changes the UI to show the number of individuals enrolled in an organization instead of the total number of enrollments.
Fixes #624

Remove duplicates when filtering individuals

---

ui/src/apollo/queries.js
ui/src/components/ExpandedOrganization.stories.js
ui/src/components/ExpandedOrganization.vue
ui/src/components/OrganizationsTable.vue
ui/src/components/Search.vue
ui/src/views/Dashboard.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR adds the number of individuals affiliated to each team on the expanded organization view. When the number is clicked,
it adds the filter to the search bar automatically, and shows the list of individuals affiliated to that team.

[ui] Show number of individuals affiliated to teams

---

ui/src/apollo/mutations.js
ui/src/apollo/queries.js
ui/src/components/DateInput.vue
ui/src/components/EnrollModal.stories.js
ui/src/components/EnrollModal.vue
ui/src/components/EnrollmentList.vue
ui/src/components/ExpandedIndividual.vue
ui/src/components/IdentitiesList.stories.js
ui/src/components/IdentitiesList.vue
ui/src/components/IndividualEntry.vue
ui/src/components/IndividualsTable.vue
ui/src/components/TeamEnrollModal.vue
ui/src/components/WorkSpace.vue
ui/src/mixins/enroll.js
ui/src/router/index.js
ui/src/styles/index.scss
ui/src/views/Individual.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR adds a view at `/individual/uuid` to show an individual's profile, identities and enrollments. A link to this view can be found in each individual's entry on the table, both in the buttons next to the name and in the dropdown menu.
The list of identities in the expanded individual and the modal to enroll in an organization in the table and workspace are moved to new components so that they can be also used in this view. It also adds a button on the enrollment list to add one without using drag and drop.
Closes #628.

[ui] Create view to show an individual's info

---

ui/src/components/IndividualsTable.vue
ui/src/components/Search.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR resizes the search bar on the individual's table to take up all available space. It also reorders the table's actions items on smaller device sizes so the search bar still has enough space.
1920x1080:
1366x768:
Closes  #640.

[ui] Resize search bar

---

ui/src/components/Search.vue
ui/tests/unit/search.spec.js

This PR adds a space after the text if there isn't one when adding a filter with the selector in the search field. It also adds a unit test to check this case.
Fixes #641.

[ui] Separate filters by spaces in search box

---

ui/src/components/Identity.vue
ui/tests/unit/__snapshots__/storybook.spec.js.snap

Adds an icon and explanatory text to the UUID chip in each identity to hint that the text can be copied.
The full UUID is copied on click and not only the visible part.
Closes #638.

[ui] Click to copy UUID

---

ui/src/styles/index.scss

This PR adds a stronger border above the expanded information on the individual's entries. The expanded info also keeps the white background if the entry is selected and on hover.
Fixes #636.

[ui] Separate the expanded information on the individuals entry

---

ui/src/components/IdentitiesList.stories.js
ui/src/components/IdentitiesList.vue
ui/src/components/Identity.vue
ui/src/components/Indentity.stories.js
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR adds a star next to the primary `uuid` on the identities list:
Fixes #637.

[ui] Show main UUID on the identities list

---

ui/src/components/IndividualEntry.vue
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR sets the margin on the entry avatar so the size does not depend on the individual having an organization. It also removes the space reserved for the organization if there isn't one to keep the items aligned.
Fixes #635.

[ui] Consistent margins for Individuals table entries

---

poetry.lock
pyproject.toml
releases/unreleased/new-pandas-version.yml

Update the version of Pandas to the newest version compatible with Python 3.7+.
Signed-off-by: Jose Javier Merchante <jjmerchante@bitergia.com>

Update Pandas version to ^1.3.5

---

sortinghat/cli/client/client.py
tests/cli/test_cmd_add.py

UTF-8 characters sent by the client weren't converted propertly due to an option in the JSON parser of the standard library.
By default, `json.dumps` ensures that everything is converted to ascii characters. This was problematic for emotions or other UTF-8 characters of 4 bytes. Setting the property `ensure_ascii` to `False` fixes this issue.
Tests have been updated accordingly.

Fix UTF-8 conversion on client

---

ui/src/apollo/mutations.js
ui/src/apollo/queries.js
ui/src/components/JobModal.stories.js
ui/src/components/JobModal.vue
ui/src/components/JobsTable.vue
ui/src/views/Jobs.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/queries.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/mutations.spec.js

This PR adds the ability to create jobs from the UI. Clicking the "add" button on the jobs table opens a dialog where users can select the type of job and configure the options it may have. Current jobs are `affiliate`, `genderize` and `unify` and are applied to all individuals. This makes trying to create the `unify` job fail since selecting specific source UUIDs is mandatory.

[ui] Interface to create jobs

---

sortinghat/app/urls.py
sortinghat/core/decorators.py
sortinghat/core/views.py
ui/src/App.vue
ui/src/router/index.js
ui/src/views/ChangePassword.vue

This PR adds a form where users can change their password at `/change-password` from the UI, and a Django view at `/password_change` to process the request.
Example request:
```
curl -XPOST 'http://XXX/password_change/' \
--header 'X-CSRFToken: XXX' \
--header 'Cookie: csrftoken=XXX' \
--header 'Authorization: JWT XXX' \
--form 'old_password="XXX"' \
--form 'new_password1="XXX"' \
--form 'new_password2="XXX"'
```
Fixes #664.

Change user password

---

ui/.storybook/main.js
ui/src/components/IndividualCard.stories.js
ui/src/components/IndividualCard.vue
ui/src/components/Recommendation.stories.js
ui/src/components/Recommendations.vue
ui/src/components/WorkSpace.vue
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR adds the `Recommendations` component, which includes a button and a modal opened by clicking it to show merge recommendations that can either be accepted or skipped.
The component is not yet added to the app, but can be seen in Storybook.
The PR also adds some options to `IndividualsCard` needed for the recommendations interface (removing the close button and the ability to select the card). To better show all the available options in this component and how the look together, I used the knobs package for Storybook that was already installed.

[ui] Show merge recommendations

---

.github/workflows/tests.yml
ui/package.json
ui/tests/unit/queries.spec.js
ui/yarn.lock

This PR sets the supported Node.js versions to 14 and 16, which will be [maintained until September 2023](https://github.com/nodejs/release#release-schedule). Vue 2 doesn't require any particular version, but Vue 3 will only work with v16 and higher.

Upgrade Node version

---

ui/src/router/index.js
ui/vue.config.js

This change allows us to deploy SortingHat UI in a sub-path
(https://localhost:8000/sortinghat) instead of root
(https://localhost:8000)

[ui] Allow deploy SortingHat in a sub-path

---

ui/src/main.js
ui/vue.config.js

For production deployments, the API of SortingHat will be under '/identities' path. Therefore, the path of the API will be '/identities/api'.
This is a temporary solution. We will try to make the deployment of SortingHat more flexible, so instances can use different paths and configurations where the SortingHat service will running.
Signed-off-by: Santiago Dueñas <sduenas@bitergia.com>

[ui] Fix the endpoint of the SortingHat API in production

---

ui/package.json
ui/yarn.lock

Resolves the nested loader-utils dependencies to 2.0.4.
Signed-off-by: Eva Millán <evamillan@bitergia.com>

[ui] Bump loader-utils to 2.0.4

---

ui/package.json
ui/yarn.lock

Resolves the nested thenify dependency to 3.3.1.
Signed-off-by: Eva Millán <evamillan@bitergia.com>

[ui] Bump thenify to 3.3.1

---

poetry.lock
pyproject.toml

This commit updates the version of `setuptools` without restrictions to be compatible with other packages that has the same constraints.

Update setuptools version to >65.5.0

---

README.md
docker/server-entrypoint.sh
releases/unreleased/migration-command-for-sortinghat-0.7.yml
sortinghat/server/sortinghat_admin.py
sortinghat/server/utils/create_sh_0_7_fixture.py

This commits includes a new command in sortinghat-admin command to migrate the old database schema from SortingHat 0.7 to the new 0.8 version.
If the database schema is old, it creates a migration of the data, moves the database to a new database with `_backup`, initializes the database, and restores the data using the new schema.
Closes https://github.com/chaoss/grimoirelab-sortinghat/issues/726

Migrate SortingHat 0.7 schema on Docker startup

---

.github/workflows/docker-image.yml

This PR builds the Docker images for the worker and server and push the images to DockerHub. Both images are signed with sigstore and available for for arm64 and amd64.
It is required to configure an environment 'docker-release' with the following environment variables:
- DOCKERHUB_USERNAME
- DOCKERHUB_TOKEN
- COSIGN_PRIVATE_KEY
- COSIGN_PASSWORD

[docker] Build and push Docker images

---

releases/unreleased/fix-search-syntax-link.yml
ui/src/components/Search.vue

This PR changes the link to the search syntax view on the search bar from a plain `href` to use Vue Router's `to` prop, which prepends the base path (`/identities` in production).
Fixes #735.

[ui] Fix search syntax link

---

.github/workflows/release.yml
.github/workflows/tests.yml

Pinning node to 16.x ensures GitHub Actions is not going to use node 18 or later.

Set node version to 16.x

---

.github/workflows/docker-image.yml
.github/workflows/release.yml

The action `actions/download-artifact` was using a wrong hash, update with the latest version available.

[ci] Fix typo on download-artifact version

---

.github/workflows/docker-image.yml

To build the UI we need NodeJS 16. The current version of the workflow is using 18.x. This commit forces to use 16.x.

Set NodeJS version to 16.x on Docker workflow

---

.github/workflows/release.yml
releases/unreleased/static-not-included-in-wheel-package.yml

This PR disables the checkout step in the build action to include the JS static files built in the action.

[ci] Do not checkout repository in build action

---

.github/workflows/docker-image.yml

This PR disables the checkout step in the docker build action to include the JS static files in the Python package.

[ci] Do not checkout repository in docker action

---

releases/unreleased/tenant-selection-in-job-fixed.yml
sortinghat/core/decorators.py

This PR fixes an error that was caused when the context of a Job wasn't defined as keyword argument and the tenant was not selected correctly.

[tenants] Fix tenant selection in job context

---

releases/unreleased/sort-jobs-from-newest.yml
sortinghat/core/jobs.py

Sorts the list of jobs from newest to oldest to show running jobs first.

[jobs] Sort jobs from newest to oldest

---

releases/unreleased/sortinghat-database-performance.yml
sortinghat/core/schema.py

This PR updates the way objects are counted using `query.count()` instead of `len(query)`.
This improves performance by an order of magnitude because objects don't need to be fetched.

Improve SortingHat database performance

---

releases/unreleased/job-timeout-updated.yml
sortinghat/core/schema.py

The jobs failed because they exceeded the default timeout while running tasks involving numerous identities. To ensure successful completion, adjust the timeout setting to an infinite duration, allowing jobs to finish without interruptions.

[jobs] Add infinite job timeout

---

releases/unreleased/performance-improved-for-recommendations-and-merging-jobs.yml
sortinghat/core/recommendations/matching.py
tests/test_jobs.py

This PR updates the way unify job fetches all the individuals from the database. Instead of retrieving identities from each individual, fetch all the identities at once.

[unify] Fix unify job performance

---

releases/unreleased/buttons-on-hover.yml
ui/src/components/IndividualEntry.vue

Makes the buttons to lock an individual or mark it as bot visible when the mouse is over the table row instead of just the name.
Fixes #787.

[ui] Show hiden buttons when the mouse is over the table row

---

releases/unreleased/filter-by-org-full-name.yml
sortinghat/core/schema.py
tests/test_schema.py

This PR changes the `enrollment` filter of the `individuals` query to only match the organization's full name. This fixes the issue with some organizations showing more members than they actually have.

[schema] Match organization's full name in enrollment filter

---

releases/unreleased/add-org-to-individual.yml
ui/src/components/ExpandedIndividual.vue
ui/src/components/IndividualsTable.vue
ui/src/views/Individual.vue

This PR fixes the issue with adding an organization to an individual using the "+ ADD" button on the table expanded item.

[ui] Fix enrollment in expanded individual

---

releases/unreleased/show-organizations-members.yml
ui/src/components/IndividualsTable.vue
ui/src/components/Search.vue
ui/src/views/Dashboard.vue

Fixes the issue with the individuals table showing the unfiltered list instead of the members of a team or organization when the button is clicked several times.

[ui] Fix filter by enrollment when clicking several times

---

sortinghat/core/errors.py
tests/test_errors.py

While investigating error messages when attempting to build this, the non-interplotated messages were leaking into the API. Further more, message being non-interplotated, and msg being interplotated felt backwards to me, so I've switched them around, and I've also hidden msg to _msg to make it a little clear that it's an internal detail only.

Switch around BaseError.message and msg

---

releases/unreleased/subdomain-affiliation-error.yml
sortinghat/core/recommendations/affiliation.py
tests/rec/test_affiliations.py

This PR prevents the affiliation jobs from matching subdomains if the domain is not marked as `top_domain`.
Fixes #805.

[affiliation] Fix subdomain affiliation when it's not top domain

---

releases/unreleased/manage-app-settings.yml
ui/src/App.vue
ui/src/apollo/mutations.js
ui/src/apollo/queries.js
ui/src/components/TasksTable.stories.js
ui/src/components/TasksTable.vue
ui/src/router/index.js
ui/src/views/Jobs.vue
ui/src/views/SettingsGeneral.vue
ui/src/views/SettingsLayout.vue
ui/src/views/SettingsSync.vue
ui/tests/unit/__snapshots__/mutations.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR adds a `Settings` section where users can manage the `affiliate` and `unify` tasks. `Import identities` and `jobs` are also moved to this section .

UI to manage settings

---

releases/unreleased/api-method-to-create-task.yml
releases/unreleased/delete-task-on-error.yml
sortinghat/core/api.py
sortinghat/core/jobs.py

This PR adds an API function to create scheduled tasks and fixes the issue with the tasks that have no enqueued job due to a Redis connection error when they are created.

Delete scheduled tasks with no job due to Redis connection error

---

releases/unreleased/strict-criteria.yml
sortinghat/core/jobs.py
sortinghat/core/recommendations/matching.py
sortinghat/core/schema.py
tests/rec/test_matches.py
tests/test_jobs.py
tests/test_schema.py
ui/src/apollo/mutations.js
ui/src/components/JobModal.vue
ui/src/components/MatchesModal.vue
ui/src/views/Individual.vue
ui/src/views/Jobs.vue
ui/src/views/SettingsGeneral.vue

This PR adds the `strict` parameter to the merge recommendations, which evaluates if the individual's names and emails are valid when looking for matches. This is enabled by default.
Fixes #812.

Strict criteria for merge recommendations

---

releases/unreleased/text-field-to-upate-enrollment-dates.yml
ui/src/components/EnrollmentList.vue

This PR replaces the calendar in the modal to update enrollment dates with the `DateInput` component, which features both a calendar and a text field.
Fixes #819.

[ui] Text field to update enrollment dates

---

releases/unreleased/cache-individuals-table-data.yml
ui/src/apollo/mutations.js
ui/src/apollo/queries.js
ui/src/main.js

This PR sets the fetch policy of the individuals queries to `cache-first`. When a mutation changes the data of a cached query, Apollo uses the returned data to update the cache automatically, so no refetching is needed. Apollo can't update the queries if items are added or removed from a list, so after a merge, unmerge, create or delete, or if the query was sorted by `lastModified` or was filtered by an organization that was added or removed from the individual, the queries need to be refetched.
Fixes #821

Cache individuals queries to avoid reloading the table

---

releases/unreleased/recommendations-last-modified.yml
sortinghat/core/jobs.py
sortinghat/core/recommendations/matching.py
sortinghat/core/schema.py
tests/rec/test_matches.py
tests/test_jobs.py
tests/test_schema.py

Adds the `last_modified` parameter to the jobs and mutations for the merge and affiliation recommendations. This generates recommendations only for the individuals that have been updated after that date.
Resolves #813

Recommendations for individuals modified after a date

---

.github/workflows/docker-image.yml

This commit updates the version of the cosign installer action to 3.1.2.

[gha] Update cosign-installer action to v.3.1.2

---

releases/unreleased/fix-individual-page-not-loadingd.yml
ui/src/store/index.js
ui/src/views/Individual.vue

This PR fixes the issue with the individual's page not loading. It initializes the workspace as an empty array if there is not one saved on the local storage. The individual's view also checks if the workspace exists before checking for the individual to prevent the view from not loading if there is no workspace.

[ui] Fix uninitialized workspace

---

releases/unreleased/gitdm-identities-importer.yml
sortinghat/core/importer/backends/gitdm.py
sortinghat/core/jobs.py
tests/importer/data/gitdm/gitdm_email_aliases_valid.txt
tests/importer/data/gitdm/gitdm_email_to_employer_invalid.txt
tests/importer/data/gitdm/gitdm_email_to_employer_valid.txt
tests/importer/test_gitdm.py
tests/test_jobs.py

Create a new SortingHat identities importer for Gitdm format.
This backend is configured with three parameters:
- URL pointing to the file that matches emails with organizations
- Optional URL for an aliases file that associates emails
- A flag for email validation to verify the validity of the provided email addresses.

[gitdm] Gitdm identities importer

---

releases/unreleased/open-calendar-to-the-side-of-the-date-input.yml
ui/src/components/DateInput.vue
ui/src/components/EnrollmentList.vue

This PR changes the position of the affiliation date calendar to open on the right side of the date input to avoid covering it.
Fixes #838

[ui] Move date picker to the side of the input

---

releases/unreleased/performance-on-affiliation-recommendations-improved.yml
sortinghat/core/jobs.py
sortinghat/core/recommendations/affiliation.py

The current algorithm was running unnecessary calls to 'find_individual_by_uuid' when the generic affiliation job was called. In other words, when the list of individuals to affiliate was all the individuals in the database.
To improve it, we have followed the same approach we did with the matching recommendations. We get the full list of individuals with a direct query using Django's API.

[affiliation] Improve performance of affiliation jobs

---

releases/unreleased/improve-readability-of-form-options.yml
ui/src/components/JobModal.vue
ui/src/styles/index.scss

This PR replaces the select field for the `unify` and `recommend matches` jobs with checkboxes to improve UX.

[ui] Improve job criteria form UX

---

releases/unreleased/improve-loading-time-when-looking-for-organizations.yml
ui/src/apollo/queries.js
ui/src/components/OrganizationSelector.vue
ui/src/views/Individual.vue
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR changes the `OrganizationSelector` component used to affiliate individuals to only make a request after 500ms after the last key press. The query is also changed to a cached one that only returns the organizations names instead of all their data to make it faster.

[ui] Improve organization selector loading times

---

poetry.lock
pyproject.toml

This change is to keep packages aligned with the same version. Perceval requires urllib3 v1 because there is a bug with dulwich and urllib3.

Pin urllib3 to ^1.26

---

releases/unreleased/unify-identities-with-same-source.yml
sortinghat/core/jobs.py
sortinghat/core/recommendations/matching.py
sortinghat/core/schema.py
tests/rec/test_matches.py
tests/test_jobs.py
tests/test_schema.py
ui/src/apollo/mutations.js
ui/src/components/JobModal.vue
ui/src/views/Jobs.vue
ui/src/views/SettingsGeneral.vue

This PR includes a new option to unify and recommend identities that share the defined criteria (name, username, email) and the source.
The option is called `match_source` when creating the job.

Option to match individuals with the same source

---

.github/workflows/tests.yml
README.md
config/settings/devel.py
releases/unreleased/csrf-token-only-required-from-ui.yml
sortinghat/app/urls.py
sortinghat/cli/client/client.py
sortinghat/core/decorators.py
sortinghat/core/views.py
tests/test_client.py
ui/cypress.config.js
ui/package.json
ui/public/index.html
ui/src/App.vue
ui/src/main.js
ui/src/store/index.js
ui/src/views/Login.vue
ui/tests/e2e/specs/spec.cy.js
ui/tests/e2e/support/commands.js
ui/vue.config.js

This PR changes how the CSRF token header is used. API calls using the JWT authorization header don't need the CSRF token. The token is only required on requests that are made from the UI, which now uses a new endpoint at `/api/login` to authenticate users instead of JWT. Django sets a `csrftoken` cookie when the interface is loaded and a `sessionid` cookie for authenticated users that is not available to JavaScript and includes it automatically in all requests.
Since the UI needs to be served by Django to get the token, to run it for development use `yarn watch` instead of `yarn serve`, which watches for changes and rebuilds the static files, and serve it with `./manage.py runserver `, which collects the files automatically.

Fix CSRF token header usage

---

releases/unreleased/display-individuals-most-recent-organization.yml
ui/src/components/IndividualCard.vue
ui/src/utils/actions.js
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR changes the organization displayed under the individual's name to be the latest affiliated one instead of the oldest.

Select most recent affiliation as main organization

---

releases/unreleased/fix-api-url-to-change-password.yml
ui/src/store/index.js
ui/src/views/ChangePassword.vue

This PR changes the login and change password URLs to use the public path as a base if no API URL was specified, eg. `/identities/` in production.
Fixes #851.

[ui] Fix API URLs to login and change password

---

releases/unreleased/authentication-required-fixed.yml
sortinghat/core/decorators.py
tests/test_schema.py

When the AUTHENTICATION_REQUIRED setting is set to False, the authorization decorators allow any user to take any action.

Fix AUTHENTICATION_REQUIRED setting

---

releases/unreleased/create-django_sessions-table.yml
sortinghat/core/middleware.py

Adds the `sessions` app to the tenant database router to create the `django_sessions` table on the default database to fix the `Table 'django_session' doesn't exist` error. For existing databases, run the following commands to create the table:
```
django-admin migrate --fake sessions zero
django-admin migrate
```

Fix missing 'django_sessions' table when using tenants

---

tests/test_aux.py

assertRaisesRegexp() is a deprecated (and as of Python 3.12, removed) alias of assertRaisesRegex(). Switch to it to avoid future problems.

Switch to self.assertRaisesRegex()

---

releases/unreleased/recommendation-job-fixed.yml
ui/src/views/Jobs.vue

This PR fixes the recommend matches job when executed from the settings/job that was causing it not to recommend and match.

[job] Fix recommend matches job

---

README.md
config/settings/testing.py
config/settings/testing_tenant.py
releases/unreleased/dedicated-queues-in-multi-tenancy.yml
sortinghat/config/settings.py
sortinghat/core/errors.py
sortinghat/core/jobs.py
sortinghat/core/schema.py
tests/tenants/test_jobs.py
tests/test_errors.py
tests/test_jobs.py

So far, jobs could only run in the default RQ queue. With this change, tenant jobs can run in dedicated queues when needed.
To implement this feature, it was neccesary to update the creation of the databases and queues in the
configuration file. Also, a new auto-generated config variable named TENANTS_DEDICATED_QUEUES has been set to determine whether a tenant runs its jobs in a
dedicated queue or not.

[jobs] Define dedicated queues for tenants

---

.github/workflows/docker-image.yml

We missed to update the version of node when the docker image is created.

[docker] Set build image with node 20.x

---

releases/unreleased/profile-shows-dismissed-recommendations.yml
sortinghat/core/schema.py

Resolved issue where the profile view erroneously displayed dismissed recommendations along with availables ones. Now, only active recommendations are shown.
Closes #864

Fix profile view recommendations display

---

releases/unreleased/refetch-general-settings-after-they-are-changed.yml
ui/package.json
ui/src/apollo/queries.js
ui/src/main.js
ui/src/views/SettingsGeneral.vue
ui/yarn.lock

This PR adds the `no-cache` policy to the scheduled tasks query in order to refetch it when the tasks are created or deleted.
It also removes the Apollo Link packages since their functionality is now included in the core Apollo client.

[ui] Fix affiliate and unify cache

---

releases/unreleased/change-password-form-fixed.yml
ui/src/views/ChangePassword.vue

This PR removes an unused header in the UI causing attempts to guess the user by an invalid JWT token when multitenancy was enabled.

Fix change password form

---

.github/workflows/docker-image.yml
.github/workflows/release.yml
.github/workflows/tests.yml

This commit updates the version of the actions because some of them are deprecated because Node 16 reached its end of life.

[CI] Update the version of the actions in the workflows

---

releases/unreleased/organizations-aliases-in-python-client.yml
sortinghat/cli/client/schema.py

This PR adds the aliases field to the organizations in the Python client, enabling queries for them.

[cli] Include organization aliases in the Python client

---

config/settings/devel.py
releases/unreleased/match-source-parameter-fixed-in-recommendations.yml
sortinghat/core/recommendations/matching.py
sortinghat/core/schema.py
tests/rec/test_matches.py
tests/test_jobs.py
tests/test_schema.py
ui/src/components/JobModal.vue
ui/src/views/SettingsGeneral.vue

This PR resolves an issue where the "match source" option was being applied to emails and names. With this update, this option will now only apply to usernames. Additionally, users can use email and name simultaneously.
Fixes #875

Fix unify individuals with the same username and source

---

releases/unreleased/link-to-github-profile.yml
ui/src/components/Identity.vue
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR adds a link to the GitHub profile on the username, both on the individual's profile page and in the individuals data table, and improves the alignment of the data.

[ui] Add link to GitHub profile

---

README.md
releases/unreleased/create-and-assign-users-to-permission-groups.yml
sortinghat/config/permission_groups.json
sortinghat/config/settings.py
sortinghat/core/management/commands/create_groups.py
sortinghat/core/management/commands/set_group.py
sortinghat/core/schema.py
sortinghat/core/views.py
sortinghat/server/sortinghat_admin.py
tests/tenants/test_schema.py
tests/test_schema.py

This PR adds the `readonly` and `user` permission groups. The `user` group has add, change, delete and view permissions for all `core` models except for jobs and task scheduling. The `readonly` group only grants view permissions.
The groups and their permissions are moved to `sortinghat/config/permission_groups.json`. The location of the file can be changed with the `SORTINGHAT_PERMISSION_GROUPS_LIST_PATH` environment variable.
The PR also adds a command to assign a user to a group:
```
$ sortinghat-admin set-user-group username group
```

Add readonly and read/write permission groups

---

releases/unreleased/save-url-to-an-individuals-linkedin-profile.yml
ui/src/apollo/mutations.js
ui/src/components/Identity.vue
ui/src/utils/actions.js
ui/src/views/Individual.vue

This PR adds a button to add or remove a LinkedIn identity on the individual's page actions menu. The link is displayed under the individual's name and affiliation on top of the page, along with the GitHub profile, to make them easier to access.

[ui] Add LinkedIn profile on the individual's page

---

releases/unreleased/consistent-date-format.yml
ui/.storybook/preview.js
ui/package.json
ui/src/components/JobsTable.vue
ui/src/components/TasksTable.vue
ui/src/main.js
ui/src/plugins/dateFormatter.js
ui/src/views/SettingsGeneral.vue
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/storybook.spec.js
ui/yarn.lock

This PR makes all the job execution dates use the same `YYYY-MM-DD hh:mm` format. The format logic is moved to a plugin to avoid having a different method in each component. The date formatting is managed by the `dayjs` library, which was already installed as a peer dependency.
Fixes #901.

[ui] Use consistent date format for jobs

---

docker/worker-entrypoint.sh
releases/unreleased/job-results-in-sortinghat.yml
sortinghat/core/jobs.py
sortinghat/core/schema.py

This PR fixes a bug that caused an empty list of job results when one of them was missing in Redis. This PR also updates the time the job results are kept to one week.
This also updates the worker entry point to receive parameters when a container runs.

Fix jobs missing from results

---

releases/unreleased/remove-merge-recommendations.yml
sortinghat/core/api.py
sortinghat/core/db.py
sortinghat/core/schema.py
tests/test_api.py
tests/test_db.py
tests/test_schema.py
ui/src/apollo/mutations.js
ui/src/components/IndividualsTable.stories.js
ui/src/components/Recommendation.stories.js
ui/src/components/Recommendations.vue
ui/src/components/WorkSpace.stories.js
ui/src/views/Dashboard.vue
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR adds an API mutation and a button on the UI to remove all unapplied recommendations.
Fixes #883.

Remove merge recommendations

---

docker/server.dockerfile
poetry.lock
pyproject.toml
tests/cli/test_cmd_config.py

This PR changes the base image to `python:3.8-slim-bullseye` and removes the installation of Python3 and associated packages from the Dockerfile. These packages were introducing a vulnerability related to `python-wheel`. This change eliminates the risk by removing the unnecessary packages and uses the official Python version.
This PR also updates the version on click to `^8.0.0` to fix a moderate vulnerability on SortingHat.

Fix moderate vulnerabilities in the base docker image and Python package

---

releases/unreleased/connection-closed-when-job-is-executed.yml
sortinghat/config/settings.py
sortinghat/core/jobs.py

RQ workers create a fork to run the function. The issue arises when, after completing the job, the MariaDB logs display the warning: `Aborted connection to db. Got an error reading communication packets`. This change ensures the database connection is closed before the fork ends, preventing the warning from appearing.

Close DB connection before job completion

---

releases/unreleased/users-permissions-migrated.yml
sortinghat/core/migrations/0009_tenant_perm_group.py
sortinghat/server/sortinghat_admin.py

The previous release included the users' permissions in the Group Django model. In the new release, they are included in the Tenant model. This code migrates the permissions for all the users.
Related to https://github.com/chaoss/grimoirelab-sortinghat/issues/849

Migrate user permissions from previous release

---

releases/unreleased/update-workspace-when-identities-are-split.yml
ui/src/components/IndividualCard.vue
ui/src/components/WorkSpace.vue
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/workspace.spec.js

This PR fixes the issue with split identities only being added to the workspace the fist time they are split.
Fixes #919.

[ui] Fix split identities only added to the workspace once

---

releases/unreleased/merge-organizations-when-adding-an-alias.yml
ui/src/components/OrganizationModal.vue
ui/src/components/OrganizationsTable.vue

This PR adds the option to merge the organizations if the new alias already exists as an organization that was missing from the "Edit organization" modal.

[ui] Merge organizations on the edit modal

---

.flake8
.github/workflows/release.yml
.github/workflows/tests.yml
README.md
docker/server.dockerfile
poetry.lock
pyproject.toml
releases/unreleased/python-version-updated.yml
sortinghat/core/jobs.py

Python 3.8 will reach its end of life in October 2024, and Python 3.9 will become the minimum version required by the project.
Update the Docker images to use Python 3.9, and GitHub workflows to run tests for Python 3.9, 3.10, 3.11 and 3.12 for future releases.
Update some pinned dependencies due to old errors that seem to have been fixed.
Related to https://github.com/chaoss/grimoirelab/issues/699

Drop Python 3.8 support

---

releases/unreleased/wrong-arrong-direction-when-merging-recommendations.yml
ui/src/components/Recommendations.vue

Currently shows `foo → bar` but direction is inverted as the resulting entity will be named `foo` instead of `bar`.
Closes #934

Correct arrow direction when merging recommendations

---

releases/unreleased/order-organizations-by-number-of-enrollments.yml
sortinghat/core/schema.py
tests/test_schema.py
ui/src/apollo/queries.js
ui/src/components/OrganizationsTable.vue
ui/src/views/Dashboard.vue
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/queries.spec.js

This PR adds the option to sort the list of organizations by number of enrollments. On the UI, the table columns are made actionable to sort by those fields and the default is enrollments by descending order, to show the organizations with the most enrollments first.
Fixes #940

Sort organizations by enrollments

---

releases/unreleased/skip-recommendations.yml
ui/src/components/Recommendations.vue

This PR adds a button on the "Review recommendations" modal to skip the current recommendation and load the next one.
Fixes #937.

[ui] Skip recommendation

---

.github/workflows/changelog.yml
.github/workflows/docker-image.yml
.github/workflows/release.yml
CONTRIBUTING.md
README.md

Update files to support the migration of GrimoireLab repositories as part of the default branch transition from master to main.

Migrate files for branch rename from master to main

---

poetry.lock
pyproject.toml

This commit updates the version of the `django-cors-headers` package to the latest version available.
This is needed to ensure compatibility with `grimoirelab-core`, which uses a newer version.

Update version of django-cors-headers

---

releases/unreleased/package-dependencies-updated.yml

Include changelog to foce a new version after updating django-cors-headers package to the latest version available.

Include changelog for updated package

---

releases/unreleased/affiliation-dates-different-from-input.yml
ui/src/components/DateInput.vue
ui/tests/unit/dateInput.spec.js

This PR fixes the issue with the affiliation input dates being different from the saved value in some timezones.
Fixes #966.

[ui] Fix dates different from input

---

releases/unreleased/allow-pasting-linkedin-url.yml
sortinghat/core/aux.py
tests/test_aux.py
ui/src/views/Individual.vue

This PR allows users to enter a URL when they add a LinkedIn profile. The input value is cleaned and only the slug of the URL is saved. A server-side validation is also added to check that a URL was not passed.
Fixes #967.

Allow pasting LinkedIn URLs

---

poetry.lock
pyproject.toml
releases/unreleased/click-package-pin-to-82.yml

The new release of Click (8.2.0) is not compatible with Python 3.9. Pin that dependency to < 8.2.0.

Pin Click package to <8.2

---

releases/unreleased/history-of-profile-changes.yml
sortinghat/core/schema.py
tests/test_schema.py
ui/src/apollo/fragments.js
ui/src/apollo/mutations.js
ui/src/apollo/queries.js
ui/src/components/ChangeLog.stories.js
ui/src/components/ChangeLog.vue
ui/src/views/Individual.vue
ui/tests/unit/__snapshots__/individual.spec.js.snap
ui/tests/unit/__snapshots__/storybook.spec.js.snap
ui/tests/unit/individual.spec.js

This PR adds a `changelog` field to the `individuals` GraphQL query, which returns a list of their 10 latest related transactions. The UI shows this list as a timeline on each individual's profile view.
Fixes #972

Add traceability to SortingHat profiles 

---

releases/unreleased/press-enter-key-to-log-in.yml
ui/src/views/Login.vue

This PR allows users to press the `Enter` key after entering the username and password to log in.
Fixes #980

[ui] Press Enter key to log in

---

releases/unreleased/recommendations-based-on-github-generated-email-addresses.yml
sortinghat/core/jobs.py
sortinghat/core/recommendations/matching.py
sortinghat/core/schema.py
tests/rec/test_matches.py
tests/test_jobs.py
tests/test_schema.py
ui/src/apollo/mutations.js
ui/src/components/JobModal.vue
ui/src/components/MatchesModal.vue
ui/src/views/Individual.vue
ui/src/views/Jobs.vue
ui/src/views/SettingsGeneral.vue

This PR adds the option to enable matching GitHub-generated emails to usernames on merge recommendations and unify jobs.
Fixes #867.

Option to match GitHub emails to usernames

---

releases/unreleased/improved-ui-for-merge-recommendations.yml
sortinghat/core/schema.py
ui/src/apollo/queries.js
ui/src/components/IndividualCard.stories.js
ui/src/components/IndividualCard.vue
ui/src/components/IndividualsTable.stories.js
ui/src/components/Recommendation.stories.js
ui/src/components/Recommendations.vue
ui/src/components/WorkSpace.stories.js
ui/tests/unit/__snapshots__/storybook.spec.js.snap

This PR changes the merge recommendations modal to show more than one at a time. The recommendations are ordered by individual so they can be grouped on the UI to manage them in batches. Users can select which recommendations to apply or dismiss using checkboxes. The list of recommendations is also paginated to improve the navigation.

[ui] Improve merge recommendations
